bindata/bootkube/manifests/00_openshift-etcd-ns.yaml, bindata/v3.11.0/etcd/ns.yaml, manifests/0000_12_etcd-operator_00_namespace.yaml, pkg/operator/v311_00_assets/bindata.go
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
=> Add node-selector annotation to namespace

Dockerfile, Dockerfile.rhel7, manifests/0000_12_etcd-operator_01_operator.cr.yaml, manifests/0000_12_etcd-operator_06_deployment.yaml, manifests/0000_12_etcd-operator_06_static_pod_demonset.yaml, manifests/0000_12_etcd-operator_06_static_sync_demonset.yaml, pkg/cmd/staticpodcontroller/staticpodcontroller.go, pkg/cmd/staticsynccontroller/staticsynccontroller.go, pkg/operator/bootstrapteardown/teardown.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/configobservation/configobservercontroller/observe_config_controller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/hostetcdendpointcontroller/hostendpointcontroller.go, pkg/operator/starter.go, pkg/operator/statuscontroller/condition.go, pkg/operator/statuscontroller/statuscontroller.go
This PR adds `cluster-etcd-operator` to CVO in an Unmanaged state. This is a temporary state until the installer changes can merge and then allows us to test scale with operator with one PR against this repo changing the `Managed` with the addition of a PR to MCO.
=> *: add ManagementState support to controllers

pkg/cmd/staticpodcontroller/staticpodcontroller.go, pkg/cmd/staticsynccontroller/staticsynccontroller.go, pkg/operator/bootstrapteardown/teardown.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/configobservation/etcd/observe_etcd.go, pkg/operator/hostetcdendpointcontroller/hostendpointcontroller.go, pkg/operator/starter.go
This fix:
- uses a dynamic informer for etcds.operator.openshift.io GVR
- a bug where etcd members were staying in Unknown state even 
after pod transitions in Running state
- creates a copy of hostendpoint before updating so there are no
side effects of using the cache.
=> pkg/cmd/*: fix openshift operator clients and host-endpoint-controller

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, pkg/cmd/render/render.go, pkg/operator/configobservation/configobservercontroller/observe_config_controller.go, pkg/operator/configobservation/etcd/observe_etcd.go, pkg/operator/hostetcdendpointcontroller/members.go, pkg/operator/hostetcdendpointcontroller/members_test.go
This PR adds support for etcd-bootstrap to have a client address that is IP vs FQDN. The reason is that customers do not want to add additional DNS records as a dependency for building clusters.
=> *: add support for IP based bootstrap endpoint

cmd/cluster-etcd-operator/main.go, pkg/cmd/waitforceo/waitforceo.go, pkg/operator/bootstrapteardown/teardown.go, pkg/operator/bootstrapteardown/waitforceo.go, pkg/operator/bootstrapteardown/waitforceo_test.go
This subcommand will be used in bootkube.sh to signal it is 
safe to destroy bootstrap vm and related resources.
It re-organises the teardown logic to reuse the same function
for removing etcd-bootstrap from etcd-membership
=> *: add subcommand wait-for-ceo

Makefile, cmd/cluster-etcd-operator/main.go, pkg/cmd/waitforkube/waitforkube.go
When the static pod starts we need to wait for kube until any containers that require a k8s client start. This ensures the container has been scheduled with kube and will contain required ENV for client creation.
=> *: add wait-for-kube command

pkg/cmd/staticpodcontroller/staticpodcontroller.go, pkg/cmd/staticsynccontroller/staticsynccontroller.go, pkg/operator/configobservation/etcd/observe_etcd.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/hostetcdendpointcontroller/members.go
**- What did I do**
1. fix part of code which was erroring on empty configmap scaling key 
2. Add checks for init container count
3. Use typed informers instead of dynamic and start the operator informer factory
**-  How to verify**
1. Install a 4.4 cluster from CI for example, registry.svc.ci.openshift.org/ocp/release:4.4.0-0.ci-2019-12-14-210519
2. Upgrade to a cluster-etcd-operator enabled cluster
**- Addresses**
- #50 
- #49 - After adding an init container (wait-for-kube), we needed to update the observation code to fix this 
**- Depends on**
#47
=> *: fix identified issues for upgrading to operator enabled cluster

Dockerfile, Dockerfile.rhel7, manifests/0000_12_etcd-operator_01_operator.cr.yaml, pkg/cmd/staticsynccontroller/staticsynccontroller.go
This PR effectively adds the `cluster-etcd-operator` to the CVO operator payload and set it to a Managed state.
We also are reverting the static-sync controller to utilize a generic operator informer and remove it from `WaitForCacheSync`. This is only a short term precaution as we observed a failure case in testing where WaitForCacheSync appeared to be blocking the actions of the controller which are vital to the bootstrapping process.
=> *: add cluster-etcd-operator to CVO operator payload

pkg/cmd/waitforceo/waitforceo.go, pkg/operator/bootstrapteardown/teardown.go, pkg/operator/bootstrapteardown/waitforceo.go, pkg/operator/bootstrapteardown/waitforceo_test.go, pkg/operator/clustermembercontroller/clustermembercontroller.go
With cluster-etcd-operator the `host-etcd `endpoint is dynamic,
i.e. it changes are the etcd cluster scales. This leads to a change of
etcd storage config in cluster-kube-apiserver-operator, everytime
host-etcd is updated with scaling change.
The kube-apiserver is started with bootstrap etcd storage endpoint.
We saw problems were bootstrap was ripped off before waiting for 
KAS to have valid storage config leading to loss of control plane.
This waits for atleast 1 kube-apiserver to a storage URL more than
just the bootstrap IP before removing the bootstrap node from etcd
cluster.
=> *: wait for KAS rollout to succeed before cutting bootstrap

pkg/cmd/staticsynccontroller/staticsynccontroller.go, pkg/operator/bootstrapteardown/waitforceo.go
The `rest.InClusterConfig()`[1] in discovery init-container only uses
`token` and `ca.crt`[2].
It was observed that `service-ca.crt` was the last file to be synced.
Since the sync loop would error out at not finding that file, it would take
a long time for the `token` to be synced as well, which is the true 
dependency of the discovery init container. [3]
Apply the same logic to sync loop of waiting for KAS to have valid config,
hopefully another step forward in reducing the waiting time.
This is expected to significantly reduce the bootstrap time.
1. https://github.com/openshift/machine-config-operator/blob/4932c47c7b741cf402e44dbdb2cb5af22c09156b/cmd/setup-etcd-environment/run.go#L336
2. https://github.com/openshift/machine-config-operator/blob/4932c47c7b741cf402e44dbdb2cb5af22c09156b/ve …
=> Bug 1796965: *: reduce the bootstrap time by fixing implementation details

manifests/0000_90_etcd-operator_03_servicemonitor.yaml
These metrics were Deprecated in kubernetes v1.14.
See changelog -> https://github.com/kubernetes/kubernetes/blob/5e0f36705ef785a80955bd2b6412d9d227ff60da/CHANGELOG-1.14.md#deprecated-metrics
=> Bug 1797491: manifests: Drop Deprecated etcd metrics

pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/hostetcdendpointcontroller/hostendpointcontroller.go, pkg/operator/hostetcdendpointcontroller/hostendpointcontroller_test.go
With #66, it was seen that for some clusters it takes quite a long
time for the updated etcd storage URLs to be reflected in kube-
apiserver config. This fix adds a temporary relief by starting the KAS 
rollouts with all the 4 endpoints. We leverage the etcd client load
balancer to bounce to other endpoints if an endpoint is not working
This PR also adds more informers to clustermembercontroller.go,
making the sync loop on it run more frequently.
=> Bug 1797122: add hack for KAS rollouts, make cmc chattier

bindata/etcd/pod.yaml, go.mod, go.sum, pkg/operator/etcd_assets/bindata.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/etcd_env.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/bindata/bindata.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
```yaml
containers:
- command:
- /bin/sh
- -c
- |
#!/bin/sh
set -euo pipefail
echo "NODE__NAME=ip-10-0-156-14.ec2.internal"
echo "NODE__ENVVAR_NAME=ip_10_0_156_14_ec2_internal"
echo "NODE_NODE__ENVVAR_NAME_ETCD_DNS_NAME=${NODE_ip_10_0_156_14_ec2_internal_ETCD_DNS_NAME}"
echo "NODE_NODE__ENVVAR_NAME_ETCD_NAME=${NODE_ip_10_0_156_14_ec2_internal_ETCD_NAME}"
echo "NODE_NODE__ENVVAR_NAME_IP=${NODE_ip_10_0_156_14_ec2_internal_IP}"
sleep 24h
```
```
NODE__NAME=ip-10-0-156-14.ec2.internal
NODE__ENVVAR_NAME=ip_10_0_156_14_ec2_internal
NODE_NODE__ENVVAR_NAME_ETCD_DNS_NAME=etcd-1.test02051.devcluster.openshift.com
NODE_NODE__ENVVAR_NAME_ETCD_NAME=etcd-member-ip-10-0-156-14.ec2.internal
NODE_NODE__ENVVAR_NAME_IP=10.0.156.14
```
proof of node selection
=> bug 1800313: add env vars

go.mod, go.sum, vendor/github.com/openshift/build-machinery-go/OWNERS, vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk, vendor/github.com/openshift/build-machinery-go/make/lib/version.mk, vendor/modules.txt
builds are failing which are resolved by this bump.
>vendor/github.com/openshift/build-machinery-go/make/targets/golang/../../lib/golang.mk:22: *** `go` is required with minimal version "1.13.5", detected version "1.13.4". You can override this check by using `make GO_REQUIRED_MIN_VERSION:=`.  Stop.
https://github.com/openshift/cluster-etcd-operator/pull/109/files#diff-17442a53a3318d07cc4c974c17dce448R20
=> Bug 1801344: vendor: bump build-machinery-go

go.mod
I just noticed we dif not bump go version. If CI is building testing and shipping in 1.13 so should we.
=> Bug 1801299: go.mod: bump go version 1.13

pkg/cmd/waitforkube/waitforkube.go
When we added `wait-for-kube` we made poor assumptions that we always want to wait. In certain circumstances such as disaster recovery or lights-out situations where all master nodes go down kube will never be available before etcd starts.
This PR resolves this chicken and egg by not waiting if an etcd datafile exists. In this case we can assume that etcd has been previously initialized. Thus we no longer should depend on kube to start.
blocks https://github.com/openshift/machine-config-operator/pull/1428
=> Bug 1797897: pkg/cmd/waitforkube: don't wait if etcd has previously been initialed as member

pkg/operator/hostendpointscontroller/host_endpoints_controller.go
fix minor comments in https://github.com/openshift/cluster-etcd-operator/pull/117
=> Bug 1801984: host-etcd endpoints should always contain all etcd nodes

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
Second iteration of IPv6 support includes a refactor of render and improved unit tests.
=> Bug 1788231: pkg/cmd/render: improve IPv6 support

pkg/operator/etcdcertsigner2/etcdcertsignercontroller.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/etcd_env.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Moving away from controller config.
=> Bug 1802228:  For etcd discovery domain, watch infrastructure not controller config

pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/bootstrapteardown/waitforceo.go, pkg/operator/bootstrapteardown/waitforceo_test.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/starter.go
Make the bootstrap teardown controller stand on it's own without relying on the clustermember controller
=> bug 1801877: simplify the bootstrapteardown controller

pkg/etcdcli/etcdcli.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/starter.go
This PR 
- refactors the clustermembercontroller to use EtcdClient
interface.
- it also fixes the etcd client prematurely cancelling context
=> Bug 1802748: old clustermembercontroller: use EtcdClient interface

pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
I pointed this out in #52 and @hexfusion marked the comment resolved but then I guess accidentally didn't actually fix it...
(The addresses are passed to `net.JoinHostPort` which will add its own brackets to them, so we don't want to add our own brackets.)
/assign @hexfusion
=> Bug 1803269: render: fix listening addresses in IPv6 case

pkg/operator/targetconfigcontroller/etcd_env.go
cherry-picking this from #112. This will unblock baremetal as 
we no longer depend on `NodeInternalDNS`
fixes #115
=> Bug 1801898: remove dependency on node internal DNS name

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/guardbudget/guard_budget_controller.go
builds on https://github.com/openshift/cluster-etcd-operator/pull/157 with a goal of making the existing PDBs functional by copying the content "first" in the listing
=> bug 1801397: Make existing pdb work

manifests/0000_12_etcd-operator_06_deployment.yaml, manifests/0000_12_etcd-operator_07_clusteroperator.yaml
Prevents cvo from instantiating this operator in a hosted control plane deployment. See https://github.com/openshift/enhancements/pull/202
=> Bug 1804921: Exclude etcd operator from hosted control plane deployments

pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
Reverts openshift/cluster-etcd-operator#147
=> Bug 1804960: Revert: render: fix listening addresses in IPv6 case

pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Was looking around at a failure in CEO and noticed reference to `configmap/kube-apiserver-pod`
```
StaticPodsDegraded: pods "etcd-master-0" not found
StaticPodsDegraded: pods "etcd-master-1" not found
StaticPodsDegraded: pods "etcd-master-2" not found
InstallerControllerDegraded: missing required resources: configmaps: config-1,etcd-pod-1
TargetConfigControllerDegraded: "configmap/kube-apiserver-pod": node/master-0 missing InternalDNS
RevisionControllerDegraded: configmaps "etcd-pod" not found
```
=> pkg/operator/targetconfigcontroller: fix configmap typo

manifests/0000_12_etcd-operator_06_deployment.yaml, manifests/0000_12_etcd-operator_07_clusteroperator.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go, pkg/etcdcli/etcdcli.go, pkg/etcdcli/interfaces.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Bug 1805241 - ROKS: prevent etcd operator from being applied by CVO 
Bug 1804682 - existing PDB needs certs on disk
Bug 1805096 - Cluster etcd operator remove guard budget controller 
Bug 1802664: *: fix etcdmemberscontroller
Bug 1804439: add debugging to clustermembercontroller and clean up add bug
Bug 1804960: Revert: render: fix listening addresses in IPv6 case
=> bug 1804960: Merge 4.5 into 4.4

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, pkg/cmd/render/options/config.go, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go, pkg/etcdcli/etcdcli.go
This PR removes the `discovery` init container from the bootstrap etcd instance and replaces its functionality with observations of the local systems interfaces.
We also move to etcd-host-2 service for populating endpoints for etcdcli
=> pkg/cmd/render: populate bootstrapIP from local interfaces

pkg/dnshelpers/util.go, pkg/operator/targetconfigcontroller/etcd_env.go
before we were using the value that came from the installer, but @hexfusion's previous PR made that unreliable.
=> bug 1806723: use correct IP for bootstrap host env vars

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
The ` ${ETCDCTL} member list` will fail when all the masters
are restarted at the same time. It will be good to have the 
member list, but if we don't, we should not fail and continue
to the discovery.
=> [Bug 1807054]: fix recovery of master nodes restarting at the same time

bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
This builds on top of #197 to restore the single-member cluster. 
It can be used to make the incantation of `etcd-restore-script.sh`
with just one parameter. The INITIAL_CLUSTER will be calculated,
by the restore pod and it will perform the actual restore to be
consumed by the etcd command to follow.
Makes the steps in [here](https://github.com/openshift/enhancements/pull/226#discussion_r383055434) implementable
=> [Bug 1807493]: add the restore command to restore pod

bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/etcd_env.go
This will make the restore pod work without requiring revision
specific resources from backup.
=> [Bug 1808493]: add ca-bundles to fixed locations and use the for restore pod

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
Because the port will be held by a *different* static pod during `4.3` to `4.4` upgrades, this cannot be done in an init container like the rest.  Instead, it must be embedded in the `etcd` container itself.
This PR waits for `2379`, `2380` and `9978` to be released before starting `etcd` instance
=> waits for ports before starting etcd member

bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, go.mod, go.sum, pkg/operator/etcd_assets/bindata.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/etcd_env.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
Bug 1809682: oc rsh to an etcd pod needs to have etcdctl "just work"
Bug 1809151: bump(make sh files executable)
Bug 1809142: add ca-bundles to fixed locations and use the for restore pod
Bug 1807278: pkg/operator/targetconfigcontroller: add platform raft tunables
=>  [release-4.4] Bug 1809682: sync with master

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
Fix typo `2020-03-03T20:22:53.542500839Z /bin/bash: trap:: command not found`
ref: https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/19871/artifacts/e2e-aws-upgrade/must-gather/registry-svc-ci-openshift-org-ocp-4-5-2020-03-03-190623-sha256-ee4eae4c297a6f0c80de95d12266c61f7348349a3e72d909a294644e8371e3aa/namespaces/openshift-etcd/pods/etcd-ip-10-0-159-26.us-east-2.compute.internal/etcdctl/etcdctl/logs/current.log
=> Bug 1810276: bindata/etcd: fix etcdctl trap

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
We should not worry about conditionally doing this always add.
=> Bug 1810997: pkg/operator/etcdcertsigner: always include ::1 in cert SAN

pkg/etcdcli/etcdcli.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/starter.go
This will help figure out why on ipv6, we still see dns names
```
member={name="etcd-bootstrap", peerURLs=[https://[fd2e:6f44:5dd8:c956::18]:2380}, clientURLs=[https://[fd2e:6f44:5dd8:c956::18]:2379]
member={name="", peerURLs=[https://etcd-0.ostest.test.metalkube.org:2380}, clientURLs=[]
target={name="", peerURLs=[https://etcd-0.ostest.test.metalkube.org:2380}, clientURLs=[], err=<nil>
Adding the unstarted member to the end master-0.ostest.test.metalkube.org
```
=> add events for membership changes

bindata/etcd/etcd-snapshot-restore.sh, bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
We cannot assume /home/core/assets directory exists.
=> Manifest stopped dir should be created with "p" flag

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
etcd uses approximately 25% of master CPU in a reasonable medium
sized workload. Given a 1 core per master baseline (since CPU is
compressible and shared), assign etcd roughly 25% of that core on
each master.
4.4 bug is 1812709
=> Bug 1812583: Normalize CPU requests on masters

bindata/etcd/etcd-snapshot-backup.sh, bindata/etcd/etcd-snapshot-restore.sh, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go
Disaster recovery involves restoring to previous state. This state is defined not only by etcd but also by the static-pod resources on disk. In order to traverse time properly both need to match the actual state.
The PR does the following.
- takes a snapshot of etcd state file and backup of the last modified revision of static pod resources:
**kube-apiserver-pod**
**kube-controller-manager-pod**
**kube-scheduler-pod**
**etcd-pod**
**Assumptions**: we need to make the assumption that the latest revision is last modified . We will read the revision from static manifest itself in future z-stream. The reason for this is if we go back in time we dont want to worry about the revisions on disk for all nodes. Meaning if we have a backup of rev 2 but the cluster is currently at 4. We will not …
=> bindata/etcd: backup and restore all static pods

bindata/etcd/etcd-member-remove.sh, bindata/etcd/etcd-snapshot-backup.sh, bindata/etcd/etcd-snapshot-restore.sh, bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
Copying the DR scripts from the unconventional etcd-scripts path to /usr/local/bin, so that the user can invoke it from anywhere.
=> Copy files from etcd-scripts to /usr/local/bin for convenience

bindata/etcd/etcd-member-remove.sh, bindata/etcd/etcd-snapshot-backup.sh, bindata/etcd/etcd-snapshot-restore.sh, bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
This PR cherrypicks the following into release-4.4
93a71d00c2c105089b286713813df887e67f391a Manifest stopped dir should be created with -p flag
#265 Copy files from etcd-scripts to /usr/local/bin for convenience
=> [release-4.4] Bug 1814292: Copy files from etcd-scripts to /usr/local/bin for convenience

bindata/etcd/etcd-common-tools, bindata/etcd/etcd-member-remove.sh, pkg/operator/etcd_assets/bindata.go
This PR adds a new bash function exec_etcdctl. this allows for etcdctl commands to be run within the actual container on the host.
=> Bug 1814479: bindata/etcd: run etcdctl inside of container

bindata/etcd/pod.yaml, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/clustermembercontroller/clustermembercontroller_test.go, pkg/operator/etcd_assets/bindata.go
Add an init container that fails the pod if it has stale revision data.
This can especially occur during DR as explained in #278. 
This is a two-pronged solution:
1. Add the init container that fails on bad env data
2. Modify the clustermembercontroller to not add the member unless all 
init containers have exit 0.
=> Bug 1817028: *: add an init container to stop the pod with bad revision

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
The fix for Bug 1817028 (https://bugzilla.redhat.com/show_bug.cgi?id=1817028) introduced a new init container to validate the etcd environment before firing up the etcd. However, the checks for ensuring the etcd environment rely on ipstring comparison which fail in the ipv6 environments.
=> Bug 1822326: Add extra checks for ipv6 addresses when checking the etcd env

bindata/etcd/cluster-backup.sh, pkg/operator/etcd_assets/bindata.go
The snapshot backup command must be requested for a single endpoint, and not multiple endpoints. The etcd versions of 3.3.x were forgiving but bumping to etcd to 3.4.7 fails with an error when ETCDCTL_ENDPOINTS contain multiple members.
=> Bug 1822924: The snapshot backup must be requested from a single endpoint not multiple

pkg/etcdcli/etcdcli.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go, pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go, pkg/operator/etcdmemberscontroller/etcdmemberscontroller_test.go
This PR:
1. creates a standard error message format for reporting
etcd members
2. adds specific events for unstarted members and 
unhealthy members
Since reporting available members would be at a level, 
the choice is made not report events of available members.
=> Bug 1821286: fix message reporting for etcdmemberscontroller

manifests/0000_12_etcd-operator_07_clusteroperator.yaml
since openshift/cluster-version-operator#318 merged we can have our relatedObjects created immediately so must-gather always works.
=> add relatedobjects for immediate creation by CVO

bindata/etcd/etcd-common-tools, pkg/operator/etcd_assets/bindata.go
This PR adds --authfile flag to podman create in the off chance that the container has not been pulled. As cluster-backup is run against a running etcd this seems unlikely failure but for the sake of defensive coding, I am adding.
=> Bug 1823931: bindata/etcd/etcd-common-tools pass --authfile to podman create

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
This PR adds the ability to parse the platform for the cluster
during bootstrap. Since the default for the flag is set appropriately
it is expected to work out of the box. The next step would be
explicitly supplying the flag with value in the installer and making it
required.
This also paves the way to check if libvirt and render the etcd CR
with unsupported config override from #279 eliminating the need
for manual run
=> Bug 1826140: add infra flag and configure raft for Azure

go.mod, pkg/operator/metriccontroller/client.go, pkg/operator/metriccontroller/fsync_controller.go, pkg/operator/starter.go, vendor/github.com/prometheus/client_golang/api/client.go, vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go, vendor/modules.txt
The controller added here will watch the `etcd_server_leader_changes_seen_total` metrics and get the value for last 5 minutes. If leader changes are seen (value>0), then it will query prometheus to get `etcd_disk_wal_fsync_duration_seconds_bucket` for last 5 minutes.
This is then reported as Warning event for etcd operator. In future this can become a degraded condition.
=> Bug 1827585: Add controller that watches leader changes and capture disk metrics

bindata/etcd/etcd-common-tools, pkg/operator/etcd_assets/bindata.go
The fix applied in PR https://github.com/openshift/cluster-etcd-operator/pull/314 had a typo in the authfile. This PR attempts to correct it.
=> Bug 1823931: Fix the path for authfile used for copying the etcdctl image

pkg/etcdcli/etcdcli.go, pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
etcd doesn't store the name for the unstarted members. It is initialized only when the etcd is started. So, when reporting unstarted members, currently the message appears with blank name, which can be confusing. This PR attempts to fill the name with hostname (or IP address) extracted from peer URL for the unstarted members.
=> Bug 1821286: Unstarted members cannot be blank in the log/event messages

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, pkg/cmd/render/env.go, pkg/cmd/render/env_test.go, pkg/cmd/render/render.go, pkg/etcdenvvar/etcd_env.go
This PR replaces tolerance for upstream etcd unsupported architectures `s390` and `s390x`. Because `ETCD_UNSUPPORTED_ARCH` should only be set in ENV if it is defined we took the liberty of making the `env:`  section of the bootstrap static pod spec more inline with what we do with the etcdenvvar controller.
This will make future changes to runtime env's much easier to add and manage.
=> Bug 1825667: pkg/cmd/render: add support for s390 and s390x arch

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
etcd peer certs in 4.3 contained wildcard. this PR fixes a typo which only included DNS name `etcdDiscoveryDomain` vs  `"*." + etcdDiscoveryDomain`
Because peerURLs contained domains in 4.3 we can see TLS errors like below during upgrade.
```
2020-05-01T18:36:37.0791842Z 2020-05-01 18:36:37.079092 E | rafthttp: failed to dial d8027fcd63ed8f3f on stream MsgApp v2 (x509: certificate is valid for localhost, mffaz1.qe.azure.devcluster.openshift.com, 10.0.0.6, not etcd-0.mffaz1.qe.azure.devcluster.openshift.com)
```
4.4 Bug https://bugzilla.redhat.com/show_bug.cgi?id=1830510
=> Bug 1830505: pkg/operator/etcdcertsigner: fix DNS SAN for peer certificates

pkg/operator/clustermembercontroller/clustermembercontroller.go
Before this change, the ClusterMemberController performed a full sync in response
to any watch event associated with a configmap in any namespace in the cluster.
This causes (at a minimum) unnecessary etcd client traffic.
This patch changes the controller to stop reacting to configmaps entirely and instead
react to changes to nodes, which was probably the original intent.
=> Bug 1832901: Stop reconciling in response to global configmap events

pkg/operator/clustermembercontroller/clustermembercontroller.go
This is a manual cherry pick of https://github.com/openshift/cluster-etcd-operator/pull/332.
=> Bug 1832919: Stop reconciling in response to global configmap events

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/starter.go
Prior to 4.4 etcd was bootstrap using SRV discovery. The result was each peer used FQDN in peer <--> peer communications. In 4.4 we regressed on upgrade support due to a typo which only signed DNS SAN for `etcdDiscoveryDomain`  vs `"*."+etcdDiscoveryDomain`. Although we migrate peers to use IP addresses there is a short window where in-between upgrade to 4.4 peer TLS auth can fail.
```golang
peerHostNames := append([]string{"localhost", etcdDiscoveryDomain}, nodeInternalIPs...)
```
This PR attempts to be more mindful of a proper SAN by using data provided in the MemberList to populate the peer FQDN explicitly instead of a wildcard. In the case of failure fallback to wildcard.
This bug only affects 4.4 as we do not want or require this functionality after we upgrade for 4.3 because we drop …
=> Bug 1830510: pkg/operator/etcdcertsigner: sign peer DNS SAN with explicit FQDN

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Reverts openshift/cluster-etcd-operator#328
=> Bug 1830505: Revert: "pkg/operator/etcdcertsigner: fix DNS SAN for peer certificates"

bindata/bootkube/manifests/00_etcd-host-service.yaml, pkg/operator/starter.go
This reverts commit 7f142f69b1fe95ffb033526256d9498a6c8dadc5 (https://github.com/openshift/cluster-etcd-operator/pull/346).
https://github.com/kubernetes/kubernetes/issues/6877
https://github.com/kubernetes/kubernetes/pull/7821
https://github.com/kubernetes/kubernetes/pull/7821#issuecomment-99344889
Deleting the service subjects the host-etcd-2 endpoint to deletion by
the Kube endpoints controller at random times now or in the future.
The service must remain to protect the existence of the endpoint given
the current design of Kube.
By deleting the service, we risk bootstrap failure through information
loss when the endpoint is deleted during bootstrapping, and churning
unnecessary endpoint revisions by recreating an endpoint Kube wants
to delete.
cc @hexfusion @retroflexer @deads2k …
=> Bug 1837103: Revert "remove dead host-etcd-2 service"

bindata/etcd/cluster-restore.sh, pkg/operator/etcd_assets/bindata.go
Currently the cluster backup script backs up static pod resources for "kube-apiserver-pod.yaml" "kube-controller-manager-pod.yaml" "kube-scheduler-pod.yaml" and "etcd-pod.yaml". However, when cluster-restore script is run, it stops all the static pods (including network pods for the bare-metal case). 
However, after the restore operation we only restore the kube static pods and etcd, but do not restore network pods (as they are not backed up originally). This results in failed cluster restore unable to scale up fully.
This PR fixes the problem by only stopping the kube static pods, leaving the network pods to continue to run.
=> Bug 1835146: Cluster restore should not stop network pods on bare-metal

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
etcd certs are documented to be signed for 3 years, due to a typo they have been signed for 10. This PR ensures all future certs have the accurate signing period.
ref: https://github.com/openshift/openshift-docs/issues/22253
=> Bug 1837594: pkg/operator/etcdcertsigner: sign etcd certs for 3 years

bindata/bootkube/manifests/00_etcd-endpoints-cm.yaml, pkg/etcdcli/etcdcli.go, pkg/etcdenvvar/envvarcontroller.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/starter.go
Kube service design asserts `endpoint` resources cannot exist without a corresponding `service` resource, and Kube will actively delete the endpoint when the service is deleted or if Kube detects the endpoint is a "stray".
The operator needs to:
1.  Manage etcd endpoint state atomically.
2. Maintain exclusive ownership of the etcd endpoint state resource.
Altogether this makes the `endpoint` resource inappropriate for the task. The competition between the operator and the Kube endpoints controller to manage the endpoint has led to instability.
To resolve the problems, persist etcd endpoint state in a `configmap`.
Maintain compatibility by continuing to write the `endpoint`, and update consuming components to prefer the `configmap` over the `endpoint`.
Also requires: …
=> Bug 1836927: Replace etcd endpoint representation with configmap

.gitignore, Makefile, go.mod, go.sum, vendor/github.com/openshift/build-machinery-go/go.mod, vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk, vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh, vendor/modules.txt
Once telepresence has been installed (see the run-telepresence.sh script for instructions), `make telepresence` will replace the operator's pod with a local process that has access to the same environment as the pod. This can speed up development since iteration doesn't require cycles of image build/push/pull. See https://telepresence.io for more details.
=> Bug 1834852: Add make target to run operator with telepresence

cmd/cluster-etcd-operator/main.go
A hack to eliminate the superfluous grpc connection log spam. Warnings and
errors are still emitted.
https://github.com/kubernetes/kubernetes/issues/80741
https://github.com/kubernetes/kubernetes/pull/84061
=> Silence grpc connection log noise

go.mod, pkg/etcdcli/etcdcli.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go, vendor/k8s.io/utils/diff/diff.go, vendor/k8s.io/utils/field/path.go, vendor/modules.txt
After bootstrap completes, forget the bootstrap etcd member IP by clearing
the annotation from the endpoint configmap. Otherwise the etcd client will
continue failing to connect to the dead bootstrap node forever.
=> Bug 1832923: Forget bootstrap etcd member IP after bootstrap

manifests/0000_12_etcd-operator_06_deployment.yaml
Update the operator command so that when the metrics serving certificate or key
is modified, the operator restarts to pick up the new contents.
=> Bug 1812570: Restart operator when metrics serving cert is modified

bindata/etcd/cluster-backup.sh, pkg/operator/etcd_assets/bindata.go
This PR adds error handling to assist user in understanding that the backup script is not located on a node that is able to perform backup. Also updated the script to be valid against shellcheck.
=> Bug 1842431: cluster-backup.sh: error if script dependencies are not met

bindata/etcd/pod.yaml, cmd/cluster-etcd-operator/main.go, pkg/cmd/rollbackcopy/backuputils.go, pkg/cmd/rollbackcopy/backuputils_test.go, pkg/cmd/rollbackcopy/etcdclientutils.go, pkg/cmd/rollbackcopy/fileioutils.go, pkg/cmd/rollbackcopy/rollbackcopy.go, pkg/cmd/rollbackcopy/tarutils.go, pkg/operator/etcd_assets/bindata.go
This work provides a container within the etcd pod to take periodic backups.
The immediate need for automated backups is to provide a path to upgrade from 4.4 to 4.5, with the knowledge that if the upgrade fails for some reason, there is no easy path to rollback, as the etcd version 3.4.x (used in OCP 4.5) is incompatible with the etcd version of 3.3.x (used in 4.4.x). Since restoring a backup is the safest way to rollback, it is important to have automated periodical backups to protect the users from unexpected data loss in such scenarios.
=> Bug 1840531: Adding rollbackcopy subcommand

pkg/cmd/render/render.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
After 4.4 we no longer require DNS entries for etcd in SAN so lets clean that up.
requires https://github.com/openshift/cluster-etcd-operator/pull/381
required for https://github.com/openshift/installer/pull/3626/files
=> Remove etcdDiscoveryDomain

hack/shellcheck.sh
I borrowed the implementation from the cluster monitor operator. With this we can add a test to CI.
=> hack: add shellcheck

bindata/etcd/svc.yaml, pkg/operator/etcd_assets/bindata.go
remove the need for the installer to have resources like https://github.com/openshift/installer/blob/508e44b66935058f4ff7162f1d1278279ef3d383/data/data/manifests/bootkube/etcd-service.yaml and the namespace.
once this merges, we can remove the installer bits creating the same thing differently.
=> update the operator to create a complete etcd service

pkg/operator/metriccontroller/fsync_controller.go
Before this patch, leader change stats were logged at V(0) even when
the value is zero, which isn't useful. We already record an event when
the value is greater than zero.
This patch changes the leader change log to V(4) to reduce useless
log messages in the steady state while preserving the ability to enable
the log through operator configuration.
=> Bug 1847878: Reduce superfluous leader change logging

pkg/cmd/render/bootstrap_ip.go, pkg/cmd/render/bootstrap_ip_test.go, pkg/cmd/render/render.go
Before this patch, the new bootstrap IP discovery mechanism would fail bootstrapping
if no IP could be intelligently discovered. A side-effect of that is effectively
validating the machine network CIDR by asserting the bootstrap IPs ability to be
discovered within it. Because there may still be edge cases where we fail to detect
but where the old assumption to choose the "first IP" would still work, we could
introduce an undue burden to fix all existing uses of machine network CIDR even
when our fallback could continue to work in those cases.
This patch adds a fallback behavior so that when intelligent discovery fails, the
first listed IP is selected with a warning, preserving the original discovery
behavior.
This does effectively mean that clusters can still fail to bootstrap if even the …
=> Bug 1846093: Make bootstrap IP discovery backwards compatible with previous assumptions

Makefile, go.mod, manifests/0000_12_etcd-operator_08_etcdquorumguard_deployment.yaml, manifests/0000_12_etcd-operator_09_etcdquorumguard_pdb.yaml, manifests/image-references, test/e2e/etcquorumguard_test.go, test/e2e/framework/clientset.go, test/e2e/main_test.go
Migrating the quorum guard from machine-config-operator. 
Note that the TLS certs come from secrets and configmaps, instead of files from the host (MCO was using files on disk).
=> Migrate etcd-quorum-guard from MCO.

manifests/0000_12_etcd-operator_07_clusteroperator.yaml
I am curious why we would not do this.
I am wondering if it is possibly related to https://github.com/openshift/installer/pull/3626#issuecomment-664773438
=> manifests: add operand to co

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/tlshelpers/tlshelpers.go
During render, generate the certificates necessary for the bootstrap member.
Update the bootstrap pod to use the rendered certificates.
After this change, the existing asynchronous client/server based bootstrap
certificate generation mechanism should be deleted.
Extracted from @markmc's work in https://github.com/openshift/cluster-etcd-operator/pull/410.
=> Render bootstrap certificates

cmd/cluster-etcd-operator/main.go, pkg/cmd/backuprestore/backuprestore.go, pkg/cmd/backuprestore/backuputils.go, pkg/cmd/backuprestore/etcdclientutils.go, pkg/cmd/backuprestore/fileioutils.go, pkg/cmd/backuprestore/restoreutils.go, pkg/cmd/backuprestore/tarutils.go
Converting the bash scripts into Golang as subcommands to cluster-etcd-operator.
This supersedes the previous PR #398.
=> Converting cluster-backup and cluster-restore shell scripts as subcommands

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, pkg/cmd/render/render.go
Adjusts the bootstrap member pod's certificate references to use the
bootkube render output paths now that the installer has been updated
to put the rendered output in the expected locations.
Remove deprecated metrics CA flag.
=> Clean up bootstrap member cert references

docs/etcd-tls-assets.md
I found all of this quite bewildering to keep straight in my head, so I figured I'd try to write it down.
=> Document how etcd's TLS assets are managed

pkg/etcdenvvar/etcd_env.go
This PR turns on the go profiling handler by default. My intial concern with enabling this was overhead but in speaking with Clayton and further research overhead is pretty much nothing unless the handler is used.
usage example fort debugging heap.
```
oc rsh -T -n openshift-etcd etcd-ip-10-0-155-214.us-west-1.compute.internal  sh -c 'curl --cert $ETCDCTL_CERT --key $ETCDCTL_KEY --cacert $ETCDCTL_CACERT https://localhost:2379/debug/pprof/heap' > /tmp/heap
PROF_BINARY_PATH=/tmp go tool pprof /tmp/heap
```
=> pkg/etcdenvvar: enable pprof by default

pkg/cmd/render/options/config.go, pkg/cmd/render/render.go
`kube-client-agent` and `setup-etcd-environment` are no longer used lets make sure they are not required flags.
=>  Bug 1868117: pkg/cmd/render: remove kube-client-agent as required flag

pkg/operator/starter.go
This cleans up the old mco pdb after the new one is in place.  It may fight with and old MCO operator, but only until that operator gets its new deployment.
=> bug 1872802: remove old MCO etcd quorum guard resources

go.mod, pkg/etcdcli/etcdcli.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go, vendor/k8s.io/utils/diff/diff.go, vendor/k8s.io/utils/field/path.go, vendor/modules.txt
After bootstrap completes, forget the bootstrap etcd member IP by clearing
the annotation from the endpoint configmap. Otherwise the etcd client will
continue failing to connect to the dead bootstrap node forever.
Backport to 4.5.z
=> Bug 1859678: Forget bootstrap etcd member IP after bootstrap

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, vendor/github.com/openshift/library-go/pkg/operator/status/version.go, vendor/modules.txt
* openshift/library-go@71b63d85: adds audit policy configuration config map
* openshift/library-go@19c5b991: add audit policy path getter
* openshift/library-go@918750c9: allows for specifying a name for the audit policies config map
* openshift/library-go@0f5f426b: allows for specifying a path for NewAuditPolicyPathGetter function
* openshift/library-go@e26b9e23: exposes GetAuditPolicies for getting a stronly typed object
* openshift/library-go@a943da34: prefix nested observer condition to avoid racing
* openshift/library-go@e68ef472: bump(*)
* openshift/library-go@22e2f2b9: connectivitycheckcontroller: add to library-go
* openshift/library-go@07787078: csi: remove csidrivercontroller
* openshift/library-go@35c2f0bd: csi: split CSIDriverController into two
* …
=> Bug 1858763: bump(*): vendor update

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
This will have no currect effect with the default I/O scheduler
of `mq-deadline`, but I think it will help once we switch to `bfq`
as part of https://github.com/openshift/machine-config-operator/pull/1946
=> Bug 1850057: etcd-pod: Use ionice -c2 -n0

manifests/0000_12_etcd-operator_06_deployment.yaml
Rename the operator container to allow for more reasonable debugging.
=> Bug 1876858: manifests: rename operator container to be more descriptive

bindata/etcd/cluster-restore.sh, bindata/etcd/etcd-common-tools, pkg/operator/etcd_assets/bindata.go, pkg/operator/starter.go
Currently when we restore a cluster from backup, we use restore-pod.yaml from the currently installed image. This is problematic especially when switching across releases (minor or micro release versions).
=> Bug 1837540: Use restore pod yaml from the backup when restoring

manifests/0000_12_etcd-operator_08_etcdquorumguard_deployment.yaml
This commit removes timeouts for NoExecute
and NoSchedule tolerations.  This results in the
pods not being marked deleted and rescheduled in
case of a kubelet going unreachable.
=> Bug 1840358: etcd-quorum-guard remove toleration timeouts

pkg/etcdcli/health.go
Piggyback on the member health checking facility to expose the current
raft term per member as a Prometheus metric to enable more granular
performance analysis.
=> Bug 1881082: Expose etcd raft term as a metric

bindata/etcd/cluster-restore.sh, bindata/etcd/etcd-common-tools, pkg/operator/etcd_assets/bindata.go, pkg/operator/starter.go
Ths is a manual cherry-pick of #436 and an additional commit to include a fallback mechanism to copy restore pod yaml from local disk, if the backup doesn't contain it. 
This is done to support backups that were taken before the change to include restore-pod yaml in the static-pod-resources of etcd.
=> [release-4.5] Bug 1877930: Use restore pod yaml from the backup when restoring

manifests/0000_90_etcd-operator_03_servicemonitor.yaml
This patch removes Prometheus label drop rules which were erroneously carried
over from etcd or the apiserver. These rules caused debugging metrics exposed by
the operator to be inadvertently dropped.
=> Bug 1881082: remove erroneously specified label drop rules

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
`lsof` doesn't output ports in TIME_WAIT but `ss` does. Therefore, it is more reliable to use `ss` to detect the port condition.
=> Bug 1883610: Use more reliable ss in place of lsof

pkg/operator/clustermembercontroller/clustermembercontroller.go
In certain circumstances such as transient client failure followed by the operator process being killed (leader election lost) the operator can get in a situation where we forget to retry scaling members.
In this case we see the caches sync but scaling was not retried.
```
I0929 07:50:39.362608       1 shared_informer.go:223] Waiting for caches to sync for ClusterMemberController
I0929 07:50:40.862752       1 shared_informer.go:230] Caches are synced for ClusterMemberController
```
This PR ensures that we revisit membership in the case of a leaked event or unexpected cache to make sure we don't have any further work to do.
=> Bug 1883772: pkg/operator/clustermembercontroller: resync every minute

manifests/0000_12_etcd-operator_10_flowschema.yaml
Traffic from control plane operators are important (kas-o, oas-o, auth operator, etcd operator), they have a dedicated concurrency pool now.
See https://github.com/openshift/cluster-kube-apiserver-operator/pull/966 for more details.
=> flowschema for etcd operator traffic

manifests/0000_12_etcd-operator_06_deployment.yaml
enable profiler by default so we can dig deeper into performance improvements with the operator itself without any change to running operator spec or log level. pprof has no perf impact when not used so I don't see any downside to enabling by default.
usage example
```
oc rsh -n openshift-etcd-operator etcd-operator-5d46b88565-lfwdh curl --output - http://127.0.0.1:6060/debug/pprof/heap > heap
```
=> *: enable pprof profiler for operator

Dockerfile.rhel7
Updating cluster-etcd-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/cluster-etcd-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating cluster-etcd-operator builder & base images to be consistent with ART

bindata/etcd/cluster-restore.sh, bindata/etcd/etcd-common-tools, go.mod, go.sum, pkg/operator/etcd_assets/bindata.go, pkg/operator/starter.go
Ths is a manual cherry-pick of #436  and an additional commit to include a fallback mechanism to copy restore pod yaml from local disk, if the backup doesn't contain it. 
This is done to support backups that were taken before the change to include restore-pod yaml in the static-pod-resources of etcd.
The commits are identcal to #442 submitted to release-4.5.
=> [release-4.4] Bug 1877965: Use restore pod yaml from the backup when restoring

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
Surely it's not this simple...
=> Use etcd's /health endpoint for readiness checking

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/tlshelpers/tlshelpers.go
During render, generate the certificates necessary for the bootstrap member.
Update the bootstrap pod to use the rendered certificates.
After this change, the existing asynchronous client/server based bootstrap
certificate generation mechanism should be deleted.
Backport of https://github.com/openshift/cluster-etcd-operator/pull/412
=> Bug 1877374: Render bootstrap certificates

pkg/operator/starter.go
cluster-etcd-operator is now completely free of machine-config-operator dependencies with the migration of quorum-guard in 4.6. This PR cleans up some code that was required to manage the quorum-guard migration.
=> *: remove all MCO tolerations

bindata/etcd/cluster-restore.sh, bindata/etcd/etcd-common-tools, pkg/operator/etcd_assets/bindata.go, pkg/operator/starter.go
Reverts openshift/cluster-etcd-operator#436.
The original PR was created to fix a problem with restoring backups taken across versions, which was needed for 4.4 <-> 4.5 upgrades. But this also introduced a new bug which disallows backup taken on one node to be restored on a different node.
As this change is not needed for 4.6 and 4.7 reverting it.
=> Bug 1895509: Revert "Bug 1837540: Use restore pod yaml from the backup when restoring"

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
The rollbackcopier container exists to support a 4.4->4.5 upgrade. Once
4.5 is running, the container is no longer needed provided a 4.4 backup
exists prior to the upgrade, which the rollbackcopier basically assures.
The copier itself incurs a performance penalty that 4.5 users shouldn't
be subject to once the upgrade is complete.
=> Bug 1894267: Remove the rollbackcopier

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
This reverts commit b401acfb3aa0f8134f88c053d05eac1ef52ee3b2 because
it causes etcd metrics to be exposed insecurely.
Reverts https://github.com/openshift/cluster-etcd-operator/pull/474.
=> Revert "Use etcd's /health endpoint for readiness checking"

bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go
Replace the `exec` etcd readiness probe with a `tcpSocket` probe because
the `exec` version generates zombie processes in the container. The new
probe should be functionally equivalent.
=> Bug 1844727: Use socket readiness probe to avoid generating zombies

bindata/etcd/cluster-restore.sh, pkg/operator/etcd_assets/bindata.go
The current restore pod yaml has node specific URLs which makes it not usable across the cluster on any node to restore.
This PR replaces node specific values in the backup at the time of restore with the values relevant to the node on which it is being restored.
=> Bug 1897543: DR: Make restore pod yaml specific to restoring node

bindata/bootkube/manifests/00_openshift-etcd-ns.yaml, pkg/cmd/render/render.go, pkg/etcdenvvar/envvarcontroller.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/ceohelpers/unsupported_override.go, pkg/operator/ceohelpers/unsupported_override_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
Before this patch, there were two implicit etcd cluster scaling strategies
applied in different contexts. This patch make those strategies explicit
and adds a new strategy to support additional use cases.
The strategies are:
* HAScalingStrategy (default): the etcd cluster will only be scaled up when at least
3 node are available so that HA is enforced at all times. This rule applies
during bootstrapping and in the steady state.
* NonHAScalingStrategy means that during bootstrapping, the etcd cluster will
be allowed to scale when at least 2 members are available (which is not HA),
but after bootstrapping any further scaling will require 3 nodes in the same
way as HAScalingStrategy.
This strategy is selected by adding the `openshift.io/non-ha-bootstrap`
annotation to the openshift-etcd …
=> Introduce bootstrap scaling strategies

bindata/etcd/cluster-backup.sh, pkg/operator/etcd_assets/bindata.go
Currently the disruptive tests require taking backup when there is no etcd quorum. The previous PR #504 necessitated the need for the API server to be available to check the reliability of the revision being backed up.
This PR provides an option to force backup even when API is not available to check the health of each of static pods.
=> Bug 1906875: Provide an option force backup even when API is not available to check the health.

pkg/etcdenvvar/etcd_env.go, pkg/etcdenvvar/etcd_env_test.go
Today etcd will accept any cipher that was part of golang 1.12 unfortunately some of these ciphers are considered weak exposing us to vulnerabilities such as SWEET32. This PR resolved the issue by defining a default using the `TLSProfileIntermediateType`[1]. These ciphers are available in golang 1.12 -> 1.15 so apiserver will have 100% compatibility and are considered strong tls v1.2.
Currently, etcd does not provide an explicit cipher suite, the result is etcd is exposed to various exploits on week ciphers such as SWEET32.
The plans are to supersede this PR by adding a TLS observer, but we have a problem with using the kube-apiservers default for various reasons including lack of default support for tls 1.3.
[1] https://github.com/openshift/api/blob/release-4.6/config/v1/types_tlssecurity …
=> Bug 1851810: *: ensure etcd listens on strong ciphers

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go, pkg/testutils/testutils.go
Currently cluster-etcd-operator only checks the existence of the certificates, but doesn't verify the SAN configured in the certs against the current node IP address (hostname).
This PR fixes the problem by parsing the certificate to validate the SAN. If there is a SAN mismatch, it generates a new set of certificates.
=> Bug 1882176: Validate certs for the current IP address of the node

pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
Today if the `openshift-etcd` namespace is deleted the cluster will not recover as the endpoints cm resource will not be recreated. This is fatal of course because the apiserver can no longer observe the list of backend endpoints. This PR tolerates the missing configmap in the endpoints controller allowing for it to be recreated.
Closes https://github.com/openshift/cluster-etcd-operator/issues/513
=> Bug 1916853: pkg/operator: ensure etcd endpoints cm

pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
Due to a parsing bug, the bootstrap rendering logic fails to detect a usable
machine network CIDR when using IPv6 dual stack mode unless the IPv4 CIDR is the
first element in the install config's machineNetwork array, which is brittle.
This patch fixes the parsing mistake so that the IPv4 address can be located
amongst the machineNetwork CIDRs in dual stack mode.
Although ideally etcd would detect and bind to the "preferred" family and that
family would be again located here during bootstrap CIDR detection, such a
change would be more invasive. The scope of this fix is to get dual stack
reliably working even if it means using IPv4 inconsistently during bootstrapping
when IPv6 would be more consistent.
=> Bug 1907872: Make dual stack bootstrapping more reliable

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
In production environments etcd is over requested for actual use.
The bulk of that over-requesting comes from the sidecars which
overstate their actual needs. Adjust them based on the calculations
from prod clusters to request roughly 100m less CPU than before.
/hold
While we review these changes together
=> Bug 1920159: CPU requests overstate actual needs

pkg/cmd/rollbackcopy/backuputils.go, pkg/cmd/rollbackcopy/etcdclientutils.go
A valid etcd endpoint should have a valid URL scheme prefixed. 
The only reason it continues to work is because etcd client was disregarding this setting, and getting a subconn based on the environment variables.
=> Bug 1924913: A valid etcd endpoint should have the URL scheme prepended.

pkg/operator/metriccontroller/client.go, pkg/operator/metriccontroller/fsync_controller.go
4.7.0-0.nightly-2021-02-02-223803
4.7.0-0.nightly-2021-02-05-105159 CI
This PR
Closes https://github.com/openshift/cluster-etcd-operator/issues/533
=> Bug 1925586: pkg/operator/metriccontroller: cleanup transports

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
This refactor enables regenerating certs for nodes that have been removed and added back with the same name, and simplifies the addition of further checks for cert lineage and expiry.
/cc @hexfusion @retroflexer
=> Improve cert controller detection and correction of invalid certs

manifests/0000_12_etcd-operator_06_deployment.yaml, manifests/image-references, pkg/operator/quorumguardcontroller/quorumguardcontroller.go, pkg/operator/starter.go
During the migration of quorum-guard from CVO to controller managed we forgot to populate the image with an explicit image ref from the release payload.
=> Bug 1929359: pkg/operator/quorumguardcontroller: use cli image from release payload

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/starter.go, pkg/testutils/testutils.go
Collecting the certs as part of validation removes the need to depend on the informer being current.
=> Refactor creation of aggregated cert secrets

manifests/0000_12_etcd-operator_10_flowschema.yaml
Important Note: We support upgrade and downgrade - 4.7 to 4.6 downgrade would behave very badly (in a skew case). So we should NOT back port to 4.7
=> switch to v1beta1 for the p&f APIs

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, docs/etcd-tls-assets.md, pkg/cmd/render/render.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/starter.go, pkg/tlshelpers/tlshelpers.go
Writing a single secret ensures that the result of node addition or cert rotation will trigger at most a single rollout. If more than one aggregated secret needs to be written, there exists the possibility that the static pod controller could start a rollout before all secrets had been written.
/cc @hexfusion @retroflexer
=> Manage one aggregated cert secret rather than one per cert type

pkg/etcdenvvar/etcd_env.go
While this ENV is currently marked experimental it has large positive performance impacts[1]. Upstream kep[2].
cc @deads2k 
[1] https://github.com/kubernetes/kubernetes/pull/99021/files#diff-53f602f80b466ce021d5d5f8b14894997ccde64ae4d9b207296c3ca49978bdfbR555
[2] https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1904-efficient-watch-resumption
=> pkg/etcdenvvar: set periodical watch progress notification to 5s

bindata/bootkube/manifests/etcd-ca-bundle-configmap.yaml, bindata/bootkube/manifests/etcd-client-secret.yaml, bindata/bootkube/manifests/etcd-metric-client-secret.yaml, bindata/bootkube/manifests/etcd-metric-serving-ca-configmap.yaml, bindata/bootkube/manifests/etcd-metric-signer-secret.yaml, bindata/bootkube/manifests/etcd-serving-ca-configmap.yaml, bindata/bootkube/manifests/etcd-signer-secret.yaml, bindata/bootkube/manifests/openshift-etcd-svc.yaml, go.mod, pkg/cmd/render/certs.go, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go, vendor/modules.txt
Migrate tls bootstrap from the installer to ensure that changes to bootstrap, recovery or rotation of tls assets can be validated directly in ceo CI without requiring changes to the installer.
/cc @hexfusion @retroflexer
=> Migrate tls bootstrap from the installer

pkg/cmd/render/render.go
Final PR in the series cleaning up bootstrap rendering. 
Removing the defaults ensures that the operator doesn't make any assumptions about what its inputs will be. 
/cc @hexfusion @retroflexer
=> Remove deprecated render options and remove default

bindata/bootkube/manifests/00_etcd-endpoints-cm.yaml, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go, pkg/operator/ceohelpers/bootstrap.go
Currently, the bootstrap in place used with SNO adds an annotation `alpha.installer.openshift.io/etcd-bootstrap` which is intended to be used by the cluster to communicate with the bootstrap etcd instance. But bootstrap in place means that the bootstrap node will never be visible. The result is the cluster never pivots from the bootstrap node endpoint which is not expected. This change fixes that problem by adding the `BootstrapInPlaceStrategy` which omits that annotation.
=> Bug 1931658: render: refactor scaling strategies

pkg/etcdenvvar/etcd_env.go
This PR adds support for setting socket options `SO_REUSEADDR`[1] to etcd listeners via `ListenConfig`. What we have found is during etcd process restart there can be a considerable time waiting for the port to release by `TIME_WAIT` which for OpenShift is 60 seconds..
```
$ ps aux | grep etcd | wc -l
0
$  ss --numeric -o state time-wait 
tcp    0       0                 10.0.138.12:34642            10.0.138.12:2380   timer:(timewait,50sec,0)                                                       
tcp    0       0                 10.0.138.12:34470            10.0.138.12:2380   timer:(timewait,35sec,0)                                                       
tcp    0       0                 10.0.138.12:34086            10.0.138.12:2380   timer:(timewait,10sec,0) …
```
=> Bug 1927942: pkg/etcdenvvar: enable SO_REUSEADDR

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go
`capnslog` will is deprecated`zap` logger will offer much more flexibility. This PR also adds `time` to our while loop during `TIME_WAIT` for a quick summary of this MTTR timing.
```
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
```
=> Bug 1948040: *: enable zap as default logger

bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
As per @hexfusion suggestion, logLevel was not used anywhere, its intention is for users to set log-level for etcd operand itself. This PR propagates the logLevel from the etcd CR to set the `--log-level` flag.
Opening PR mainly to get feedback on the following:
I didn't change the original Custom Resource definition of logLevel, but I feel like having that be a 1:1 match to the etcd log level would be a better UX. Should I go ahead and change the `operatorSpec.LogLevel` definition? If yes, I could use some pointers, as while I am familiar with library-go, I am not familiar with the way it does the CRDs. 
cc @marun @retroflexer
=> Bug 1948553: bindata, pkg: Propagate operator log level to etcd itself

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/config/client/transport.go, vendor/github.com/openshift/library-go/pkg/controller/factory/base_controller.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/unstructured.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installerstate/installer_state_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/args.go, vendor/modules.txt
* openshift/library-go@5df90a2a: provides CancelRequest method for the PreferredHost round tripper  to facilitate cancellation
* openshift/library-go@9c9b6ed0: Allow StaticResourceController to ignore NotFound
* openshift/library-go@e2421125: Add ServiceMonitor sync to CSI operators
* openshift/library-go@04e8cf0b: Add ServiceMonitor to ApplyDirectly
* openshift/library-go@5cf97eb2: Return errors from ApplyDirectly
* openshift/library-go@73c4ea10: static-pods: allow fast-forward to next revision with pending installer
* openshift/library-go@d6342ca9: static-pods: avoid noise from 'for <duration>' messages
* openshift/library-go@2b890d20: convenience functions for processing unstructured arguments
* openshift/library-go@8c6d5ea6: static-pods: always set installer reason string
* …
=> Bug 1949418: bump(*): vendor update

bindata/etcd/ns.yaml, bindata/etcd/pod.yaml, manifests/0000_12_etcd-operator_00_namespace.yaml, manifests/0000_12_etcd-operator_06_deployment.yaml, pkg/operator/etcd_assets/bindata.go
In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> Add management workload annotations

pkg/etcdenvvar/etcd_env.go
Make sure endpoints that are returned are sorted to prevent any
unnecessary when nothing changes.
While this does not fix 1948533, I still used it to be valid bugzilla as its where this was caught. Let me know if this is incorrect I can create a separate bugzilla for this.
cc @hexfusion @mfojtik
=> Bug 1950934: pkg/etcdenvvar/etcd_env.go: Sort endpoints to prevent rollout

bindata/etcd/pod.yaml, manifests/0000_12_etcd-operator_06_deployment.yaml, pkg/operator/etcd_assets/bindata.go
As per openshift/enhancements#739, the workload annotations names are changing.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged
=> Rename workload annotations

pkg/operator/starter.go
Don't set operator version explicitly. library-go will take care of it after updating the operands. 
Setting the operator version ahead of operands will confuse the CVO and the cluster_operator_conditions metrics about what version the etcd component is at until this bug gets fixed.
=> Bug 1952266: Don't set operator version before operands update

pkg/operator/metriccontroller/fsync_controller.go
Follow up to https://github.com/openshift/cluster-etcd-operator/pull/573
=> Bug 1952684: pkg/operator/metriccontroller: check vector length

pkg/operator/starter.go
It appears rebooting a node and getting it to the point where the kubelet is running static pods can take more than the default 2 minutes. This causes etcd operator to set Degraded=True on healthy machine-config node reboots. 
I am guessing a 5 minute duration is sufficient, but it is the guesswork. I am not sure if there is any slower hardware that would take more than 5 minutes to reboot and restart the static pods.
=> Bug 1952268: Increase inertia duration for the EtcdMembersDegraded condition

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
The current unauthenticated tcpSocket readinessProbe spams the etcd logs and does not properly reflect ready status. In order for etcd to be ready to accept new requests, a quorate health check should return true. Static Pod Installer is smart enough to not install a new static pod until the existing pods are Ready. So we open up a race that could result in temporary quorum loss by not waiting until etcd is actually Ready.
```
2021-03-12 21:35:28.803656 I | embed: rejected connection from "10.0.146.252:36846" (error "EOF", ServerName "")
```
socket path includes `NODE_NODE_ENVVAR_NAME_IP` so that mTLS passes auth. etcd today requires the following format for socket path  `<name>:<port>`. By setting 2s timeouts I believe we should remove the window of opportunity for zombie process as a …
=> Bug 1946607: bindata/etcd: improve readinessProbe checks by dialing unix socket target

bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
Backport of https://github.com/openshift/cluster-etcd-operator/pull/561 to 4.7 release.
=> Bug 1954073: bindata, pkg: Propagate operator log level to etcd itself

bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go
a small change that prints revision in logs. it is generally nice to have this observability when looking at CI etc.
=> Bug 1958245: etcd/pod: print static pod revision in logs

.ci-operator.yaml, Dockerfile.rhel7, go.mod, go.sum, vendor/modules.txt
Prereq for https://github.com/openshift/release/pull/18621 to be green, i.e. don't fall over golang version skew.
=> Bug 1963871: Move back to Golang 1.15 as in o/release

.ci-operator.yaml, Dockerfile.rhel7, go.mod, go.sum
Bumping the go version to 1.16.
=> Bug 1963871: bump(*): Update the go version to 1.16

pkg/dnshelpers/util.go
Manual cherry-pick of #587 and #591.
=> [release-4.7] Bug 1958416: pkg/dnshelpers: fallback to spec if status is not populated for serviceNetwork

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
This will ensure against expired serving certs breaking the cluster.
/cc @hexfusion
=> Rotate serving certs when duration less than minimum percent

pkg/etcdenvvar/etcd_env.go
In the past the hard limit for the backend store was 8GB. This value was chosen because of the MTTR for pulling a large snapshot across the wire could cause disruption with the time it could take to have a new members db to become up to date. In etcd 3.4 that hard limit has been dropped. 
For OCP we set the `NOSPACE` alarm to fire at 7GB allowing admin a buffer between the alarm and hard limit. But since a hard limit is no longer a consideration the PR sets `ETCD_QUOTA_BACKEND_BYTES` to 8GB as it is still the recommended max.
```
2021-05-14 08:39:42.798064 W | etcdserver: backend quota 9589934592 exceeds maximum recommended quota 8589934592
```
=> pkg/etcdenvvar: bump ETCD_QUOTA_BACKEND_BYTES to 8GB

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
This refactor enables regenerating certs for nodes that have been removed and added back with the same name, and simplifies the addition of further checks for cert lineage and expiry.
Manual cherry-pick of https://github.com/openshift/cluster-etcd-operator/pull/540 due to the pick not being clean. The change is limited to the cert signer, and I have manually verified that the this PR updates the cert signer and associated unit tests to match the result of applying 540 to release-4.7. 
/cc @hexfusion
=> Bug 1965535: [release-4.6] Improve cert controller detection and correction of invalid certs

pkg/operator/starter.go
Manual cherry-pick of https://github.com/openshift/cluster-etcd-operator/pull/579 into release-4.7
=> Bug 1976988: [release-4.7]: Increase inertia duration for the EtcdMembersDegraded condition

bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go
Wanted to see the latency metrics and noticed we do not have those enabled in OpenShift. This is more aimed at 4.9, opening to check the number of series this adds to cluster Prometheus but also to not forget to enable. :)
This allows us to measure latency distributions of the RPCs. This brings in the following histogram metrics:
* grpc_server_handling_seconds_count
* grpc_server_handling_seconds_sum
* grpc_server_handling_seconds_bucket
/hold
=> bindata/etcd: Enable gRPC time histograms

jsonnet/custom.libsonnet, jsonnet/jsonnetfile.lock.json, jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
As per the https://issues.redhat.com/browse/OCPPLAN-6250 epic, message is being removed, so this replaces downstream and upstream alerting definitions with description. 
@hexfusion the only change downstream is the custom.libsonnet, rest you already reviewed upstream.
=> Replace message with description field

jsonnet/main.jsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
This is part of the alerting epic, which requires all critical alerts to have runbooks, this is done via the runbook_url field.
We can merge after https://github.com/openshift/runbooks/pull/9 this PR is merged, as right now two runbooks don't exist yet.
/hold
=> Inject runbook url into alerts

pkg/operator/defragcontroller/defragcontroller.go, pkg/operator/defragcontroller/defragcontroller_test.go
This PR provides better error handling and removes a post defrag RPC to status.
=> pkg/operator/defragcontroller: reduce RPC calls after defragmentation

jsonnet/main.jsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
The base path for runbooks in github.com/openshift/runbooks has been adjusted, this adjusts the path in `runbooks_url` accordingly
=> Adjust runbooks url to new path

bindata/etcd/quorumguard-deployment.yaml, pkg/operator/etcd_assets/bindata.go
etcd 3.5 health now responds with additional json key "reason" this breaks health checks for quorum guard. This is all very brittle and should be replaced with golang at minimum etcdctl for reasonable error handling. 
was
```
{"health":"true"}
```
now
```
{"health":"true","reason":""}
```
=> Bug 1988491: bindata/etcd/quorumguard-deployment: simplify health true matching

manifests/0000_90_etcd-operator_03_servicemonitor.yaml
The CMO is now capable of using client cert auth to scrape the metrics endpoints. Use that in our components to reduce API load and allow metrics collection when the API is down - given further authz conditions are met.
=> Bug 1986829: metrics: use client cert auth for metrics scraping

jsonnet/main.jsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
This was fixed upstream, let's enable it downstream now as well. 🤞
=> Bug 1701154: Enable etcdHighNumberOfFailedGRPCRequests alerts

jsonnet/main.jsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Reverts openshift/cluster-etcd-operator#626
This is almost-permafailing [4.9's metal-ipi blocking job][1]:
[1]: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.9-blocking#periodic-ci-openshift-release-master-nightly-4.9-e2e-metal-ipi
=> Revert "Bug 1701154: Enable etcdHighNumberOfFailedGRPCRequests alerts"

bindata/etcd/cluster-backup.sh, bindata/etcd/cluster-restore.sh, bindata/etcd/etcd-common-tools, pkg/operator/etcd_assets/bindata.go
manual cherry-pick of https://github.com/openshift/cluster-etcd-operator/pull/617 into release-4.6. This PR omits the refactor with a focus only on "validate the status of etcd snapshot."
=> [release-4.6] Bug 1979585: Validate the status of the etcd snapshot during backup and restore

pkg/etcdenvvar/etcd_env.go
Lets not scare folks with logs? Performance issues should be debugged with metrics. Logs are useful but 100ms threshold is quite common in a production cluster and does not necessarily conclude a performance issue. Moving this threshold to 200ms makes the log more of a useful potential signal.
=> Bug 1980465: pkg/etcdenvvar: warn on apply duration over 200ms

pkg/etcdcli/etcdcli.go, pkg/operator/defragcontroller/defragcontroller.go
An RPC to StatusRequest has a dependency on the member being running for dial. This PR handles this failure case and provides context to possible scaling issues.
=> Bug 1994707: pkg/etcdcli: provide clear error on status check for unstarted etcd member

test/e2e/etcdctl_test.go
See https://github.com/openshift/etcd/pull/94 for background.
/hold
=> Bug 1994986: test/e2e/etcdctl_test.go: Skip check perf test as we disabled it

pkg/cmd/monitor/monitor.go
grpc health check does not use context in here https://github.com/openshift/cluster-etcd-operator/blob/ab70a6487419774dabd514824e20f639e8a555bd/pkg/cmd/monitor/health/health.go#L108. Primary reason of this is context value is nil in here https://github.com/openshift/cluster-etcd-operator/blob/ab70a6487419774dabd514824e20f639e8a555bd/vendor/go.etcd.io/etcd/client/v3/client.go#L293. Thereby, cancellations or any other context based operations have no effect on this function.
This PR passes ctx to stick same context also for grpc health check dials.
=> Bug 1997207: Pass context into clientv3.Config to use same context

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/k8s.io/client-go/restmapper/category_expansion.go, vendor/k8s.io/client-go/restmapper/discovery.go, vendor/k8s.io/client-go/restmapper/shortcut.go, vendor/modules.txt
See https://github.com/openshift/library-go/pull/1180 and https://github.com/openshift/cluster-kube-apiserver-operator/pull/1214
@hexfusion @sttts please take a look, thanks!
=> Bug 1993800: Bump library-go to include backoff fix of installers

pkg/operator/starter.go, pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go, pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go
This PR fixes an issue with the backup controller where CVO was looking for status reported to ClusterOperator config.openshift.io/v1 but instead, we were publishing to operator.openshift.io/v1.
=> Bug 1997347: pkg/operator/upgradebackupcontroller: update cluster operator status

bindata/etcd/cluster-backup-pod.yaml, cmd/cluster-etcd-operator/main.go, pkg/cmd/verify/backupstorage.go, pkg/cmd/verify/verify.go, pkg/operator/etcd_assets/bindata.go
This PR addresses a few bugs that were missed in the original PR. The fact that logging was muted and the initcontainer was exiting 0 on failure masked the problems which did end up with a successful backup but the disk checks were not properly being performed. This also adds a fix for s390x compile errors carried from #656 thanks again @yselkowitz
=> Bug 1997347: pkg/cmd/verify: bug fixes and improvements

pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
The render command now fails when parsing placeholder IP addresses (`192.0.2.0/24`, `2001:db8::/32`).
This lets the bootstrap process fail more clearly early on rather than later when the config observers would skip over the etcd endpoints
https://github.com/openshift/cluster-kube-apiserver-operator/blob/37b25afec3e8666af6b668e979cc9299ccce62d4/pkg/operator/configobservation/etcdendpoints/observe_etcd_endpoints.go#L72
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2004081
TODO: Needs to be backported to 4.6
Also trying to reproduce the issue on master or 4.8 where cluster setup apparently doesn't fail even when the installconfig has a placeholder machine cidr.
=> pkg/cmd/render: disallow placeholder IPs

jsonnet/custom.libsonnet, jsonnet/jsonnetfile.lock.json, jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Initially, this alert was reverted as it kept firing on metal ipi clusters in CI. https://bugzilla.redhat.com/show_bug.cgi?id=1990489 For now until we get to the bottom of what is up with etcd on those clusters, and since the alert was not firing on other CI or other types we can reintroduce it back.
/hold
Still need to get a hold of metal ipi cluster to test this, or run the failing CI job.
=> Bug 1990489: Reintroduce etcdHighNumberOfFailedGRPCRequests alert for non metal ipi clusters

pkg/cmd/backuprestore/backuprestore.go, pkg/cmd/backuprestore/backuputils.go, pkg/cmd/backuprestore/etcdclientutils.go, pkg/cmd/verify/backupstorage.go, pkg/etcdcli/etcdcli.go, pkg/etcdcli/helpers.go, pkg/etcdcli/interfaces.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/defragcontroller/defragcontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
Suppress noisy logs like context cancelled or context deadline exceeded as they are confusing to users.
=> Bug 2006975: Suppress noisy logs and improve client errors

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml
This PR adds the etcdctl container to the bootstrap node etcd pod adding to the debugability of bootstrap failures.
=> bindata/bootkube/bootstrap-manifests: add etcdctl container to bootstrap-etcd

bindata/etcd/ns.yaml, pkg/operator/etcd_assets/bindata.go
Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-etcd` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz
=> podsecurity: enforce privileged for openshift-etcd namespace

pkg/dnshelpers/util.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go, pkg/operator/starter.go, pkg/testutils/testutils.go
This PR is a step towards the goal of providing more flexibility in way we communicate etcd membership to the apiserver on a revision level. First of all, we are going to now version the etcd-endpoints configmap. Membership change precludes a new revision and we want to use the etcd-endpoints data to be able to understand this during the revision and as a historical reference.
The second part moves the population of endpoints to actual etcd membership `MemberList` vs blindly using all control-plane nodes. This will prove future flexibility as OpenShift begins to overcome future scaling challenges.
The third part of this change adjusts the key used in the configmap. Today we base64 encode the IP address, while this does generate a unique key per endpoint the data is not useful. We now use …
=> pkg/operator/etcdendpointscontroller: use etcd membership to populate endpoints

bindata/etcd/quorumguard-deployment.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/quorumguardcontroller/quorumguardcontroller.go, pkg/operator/quorumguardcontroller/quorumguardcontroller_test.go, test/e2e/etcquorumguard_test.go
This PR add pod affinity for the quorum-guard pod matching k8s-app etcd. This gives us more flexibility in the future to ensure quorum-guard is scheduled to nodes where etcd static-pod has been installed.
This also will reduce the amount of time during install where quorum-guard reports health check failures while etcd is rolling out during install.
=> pkg/operator/quorumguardcontroller: add pod affinity

go.mod, pkg/etcdcli/etcdcli.go, pkg/operator/defragcontroller/defragcontroller.go
This PR improves observability by scraping etcd-opertator etcd client metrics via promethus grpc interceptors and providing matching failure events on defrag timeout/error. 
```
DefragControllerDefragmentAttempt
DefragControllerDefragmentSuccess
DefragControllerDefragmentFailure (new)
```
=> *: Improve observability of etcd client metrics and defrag controller

bindata/etcd/quorumguard-deployment.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/quorumguardcontroller/quorumguardcontroller.go, pkg/operator/quorumguardcontroller/quorumguardcontroller_test.go
#706 introduced a change that affects SNO install workflow, the pod affinity is expected to assist cluster-etcd-operator during vertical scaling which precludes HA topology. This PR gates pod affinity for quorum-guard to HA mode explicitly.
=> pkg/operator/quorumguardcontroller: set pod affinity for topology mode HA only

pkg/cmd/monitor/monitor.go, pkg/cmd/monitor/monitor_test.go
If the etcd client fails or `newMonitor` for any other reason has an error it is not handled at all which can result in panic. This PR resolves the error handling and adds a test case.
=> pkg/cmd/monitor: handle error on failed monitor

pkg/operator/defragcontroller/defragcontroller.go, pkg/operator/defragcontroller/defragcontroller_test.go
Due to an unfortunate series of events we have missed the fact that defrag is not properly disabled for non HA clusters. Because integration tests were using `BeforeTest` vs `BeforeTestExternal` it actually skipped the test... This PR resolves the test failure as well as properly gates the controller against non HA usage...
```
=== RUN   TestNewDefragController
--- PASS: TestNewDefragController (0.26s)
=== RUN   TestNewDefragController/defrag_success
leak.go:102: Found leaked goroutined BEFORE test appears to have leaked :
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
/home/remote/sbatsche/projects/openshift/cluster-etcd-operator/vendor/k8s.io/klog/v2/klog.go:1169 +0x6a
created by k8s.io/klog/v2.init.0
/home/remote/sbatsche/projects/openshift/cluster-etcd-operator/vendor/k8s.io/klog/v2/klog. …
```
=> pkg/operator/defragcontroller: ensure defrag controller is disabled for non HA tolopogy

pkg/cmd/render/env.go, pkg/cmd/render/env_test.go, pkg/cmd/render/render.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/operatorclient/interfaces.go, pkg/operator/quorumguardcontroller/quorumguardcontroller.go, pkg/operator/quorumguardcontroller/quorumguardcontroller_test.go, pkg/operator/resourcesynccontroller/resourcesynccontroller.go
This PR enables max learners to equal the desired control-plane replicas. For example, a typical HA IPI cluster would have max learners 3 while SNO would allow max learners 1 (default). Additionally, the kube-system/cluster-config-v1 configmap is now synced to openshift-etcd namespace. This simplifies access to the resource and allows the use of a single namespace informer.
=> pkg/etcdenvvar: set max learners based on desired control plane replicas

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
If dual-stack is enabled in cluster, this will cause the etcd not go
degraded, but instead the IPv6 address of Node will be skipped in the
check.
=> Bug 2039344: Do not include ipv6 node address in cert

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
This reverts commit e2e9e5c972169f145754a49654b94f6bece9e71d, reversing
changes made to d8c023e4d217aae762b99322923c68101c4b3ffd.
This was a workaround for a customer that is no longer needed.
=> Bug 2043683: Revert "Merge pull request #727 from mfojtik/fix-dual-ip"

pkg/operator/metriccontroller/fsync_controller.go
These slipped in when the threshold guard landed in 0d4883ed77 (#687).
=> Bug 2052270: pkg/operator/metriccontroller/fsync_controller: Fix "treshold" -> "thresholds" typos

pkg/etcdcli/etcdcli.go, pkg/etcdcli/helpers.go, pkg/etcdcli/interfaces.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go
previously the method required contacting with the etcd cluster to get the current list of members just to find an ID of the member that matches the given name.
however, all current callers (i.e. the bootstrapteardown, member removal controllers) of this method already have an ID of the member they want to remove.
in addition to that, it is easier to deal with an ID instead of a Name because the latter might be sometimes empty (i.e. member hasn't been started) which leads to awkward error handling in the operator.
=> changes the signature of the MemberRemove method to accept a memberID (uint64) not a Name (string)

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
picking up https://github.com/openshift/library-go/pull/1302
pick of https://github.com/openshift/cluster-etcd-operator/pull/736 into 4.10
=> bug 2053148: [release-4.10] update library-go to get rapid installer pod fixes

test/e2e/main_test.go, test/e2e/vertical_scaling_test.go
builds on https://github.com/openshift/cluster-etcd-operator/pull/732, requires https://github.com/openshift/cluster-etcd-operator/pull/737, promotes the previous test to `TestScalingUpAndDownSingleNode` which tests basic vertical scaling scenario.
This scenario starts by adding a new master machine to the cluster, next it validates the size of etcd cluster and makes sure the new member is healthy.
The test ends by removing the newly added machine and validating the size of the cluster and asserting the member was removed from the etcd cluster by contacting MemberList API.
a sample output from the test:
```
vertical_scaling_test.go:148: checking if there are any excessive machines in the cluster (created by a previous test), expected cluster size is 3, found 3 machines …
```
=> an e2e test for checking scaling up and down by one master node

pkg/operator/metriccontroller/fsync_controller.go
When there's a spike in leader elections and disk metrics, etcd can go degraded and never leave it even if the spike recedes and the cluster is ok.
https://bugzilla.redhat.com/show_bug.cgi?id=2057644
=> Bug 2057644: Fix FSyncController degraded latch

pkg/operator/ceohelpers/common.go, pkg/operator/ceohelpers/common_test.go
simply reads the desired Control Plane replica count from the cluster-config-v1 configmap in the kube-system namespace.
it will be used by https://github.com/openshift/cluster-etcd-operator/pull/742 and https://github.com/openshift/cluster-etcd-operator/pull/758
=> introduces ReadDesiredControlPlaneReplicasCount

pkg/cmd/render/env.go, pkg/cmd/render/env_test.go, pkg/etcdenvvar/etcd_env.go
Work in progress fix for: https://bugzilla.redhat.com/show_bug.cgi?id=2055833
=> Bug 2053596: Increase IBMCloud VPC heartbeat timeout to 500ms and leader election timeout to 2500ms

manifests/0000_90_etcd-operator_03_prometheusrule.yaml
during initial cluster roll-out there is enough churn that etcd
leadership will change and these alerts would result. This can
result of normal cluster installation and the alerts could cause
false concern of some problem.
this is happening more frquently in CI with OVN as the CNI,
especially in the GCP cloud (for whatever reason) and results
in extra failures in CI.
This should wait for an hour after "cluster_version" goes
initial and should provide enough time before the alert would
be much more meaningful if it came.
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>
=> no pending on etcdHighNumberOfLeaderChanges 1st 1h

pkg/operator/ceohelpers/common.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
brings back https://github.com/openshift/cluster-etcd-operator/pull/784, https://github.com/openshift/cluster-etcd-operator/pull/780/commits/85f8acd62c00af0ee9cf00800b08b43884ed5e96, pulls https://github.com/openshift/cluster-etcd-operator/pull/785/commits/880b5e8957eaf4459531ac138ceee2f2f1b323d3 (ipv6 fix) and updates `IndexMachinesByNodeInternalIP` to collect all `InternalIPs` assigned to a machine.
since `ci/prow/e2e-metal-ipi-ovn-ipv6` currently fails on `failed to create cluster: failed doing terraform init: fork/exec ocp/ostest/terraform/bin/terraform: no such file or directory` which is not related to the ipv6 issue we were chasing yesterday we are unable to verify https://github.com/openshift/cluster-etcd-operator/pull/790/commits/d08b40b6f6c862dbb0f261bebada03449042c4d7 which …
=> adds attemptToRemoveLearningMember to the cluster member removal controller 

pkg/etcdcli/helpers.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/clustermembercontroller/clustermembercontroller_test.go, pkg/operator/starter.go
This PR brings back https://github.com/openshift/cluster-etcd-operator/pull/780, pulls https://github.com/openshift/cluster-etcd-operator/pull/785 and updates `IndexMachinesByNodeInternalIP` to collect all `InternalIPs` assigned to a machine.
=> ClusterMemberController adds members whose machines are not pending deletion

pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go, pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go
[cvo#683][1], backported [to 4.10.8][3] with [cvo#753][2], pivoted the "I'm waiting for RecentBackup" message from the Failing condition to a new `ReleaseAccepted` condition (`Failing` is now focused on "am I happy with the current release reconciliation?" and now excludes "I'm concerned about the requested desired target release, which I haven't accepted yet").  Catch up by looking at the new condition.
We don't need to look at `Failing` anymore, because the cluster-version has already made the pivot to `ReleaseAccepted`, and since the cluster-version operator is the first to update, we don't need to worry about newer etcd operators vs. older cluster-version operators.
[1]: https://github.com/openshift/cluster-version-operator/pull/683/commits/7221c93dfcd19f6c1f46614cec105ba36be2f61e#diff …
=> Bug 2076793: pkg/operator/upgradebackupcontroller: Pivot from Failing to ReleaseAccepted

OWNERS
@tjungblu needs review permissions
~~Adding the rest of the etcd team to approvers under the agreement that, except for very minor/insignificant changes, the person who lgtm will not also approve and vice-versa.~~
We found that adding everyone to approvers essentially makes it so there's only one required reviewer instead of two for each change. Adding myself to approvers to limit bottlenecks for now.
=> Bug 2077160: Adding Thomas to reviewers and me to approvers

pkg/testutils/testutils.go
after this change, the formatting matches the one used by the endpoints controller
it caused the following tests to fail occasionally:
```
FAIL: github.com/openshift/cluster-etcd-operator/pkg/operator/etcdendpointscontroller TestBootstrapAnnotationRemoval/NewConfigMapAfterDeletion 0s
FAIL: github.com/openshift/cluster-etcd-operator/pkg/operator/etcdendpointscontroller TestBootstrapAnnotationRemoval/NewClusterBootstrapRemoval 0s
FAIL: github.com/openshift/cluster-etcd-operator/pkg/operator/etcdendpointscontroller TestBootstrapAnnotationRemoval/NewClusterBootstrapNodesProgressing 0s
FAIL: github.com/openshift/cluster-etcd-operator/pkg/operator/etcdendpointscontroller TestBootstrapAnnotationRemoval/NewClusterBootstrapProgressing 0s
FAIL: …
```
=> test utils changes the way endpoints data key is calculated

manifests/0000_20_etcd-operator_06_deployment.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
  "objectRef": "openshift-etcd-operator/deployments/etcd-operator",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container \"etcd-operator\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities
 (container \"etcd-operator\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"etcd-operator\" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container …
```
=> manifests/deployment: comply to restricted pod security level

go.mod, go.sum, pkg/cmd/readyz/readyz.go, pkg/etcdcli/etcdcli.go, pkg/etcdcli/etcdcli_pool.go, pkg/etcdcli/etcdcli_pool_test.go, pkg/etcdcli/health.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go, pkg/operator/defragcontroller/defragcontroller.go, pkg/operator/defragcontroller/defragcontroller_test.go, pkg/operator/starter.go, pkg/testutils/testutils.go, vendor/github.com/stretchr/testify/assert/assertion_compare.go, vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go, vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go, vendor/github.com/stretchr/testify/assert/assertion_format.go, vendor/github.com/stretchr/testify/assert/assertion_forward.go, vendor/github.com/stretchr/testify/assert/assertion_order.go, vendor/github.com/stretchr/testify/assert/assertions.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/modules.txt
there is a bug while caching the client, the order in which the endpoints are returned is not deterministic. That causes the cache client to be constantly created from scratch and invalidating the old (potentially while in use). 
the new client works in a pooling fashion, which handles the mutual exclusiveness of returning an existing or newly created client. HealthCheck+Member updates are handled during the retrieval, so is the close. Once a consumer is done, they simply return the client to the pool. 
added some more additional logging as well.
=> fix races in etcdclient

manifests/0000_90_etcd-operator_03_prometheusrule.yaml
This PR adds summary to etcd alert rules. 
According to [Enhancement](https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#style-guide), all prometheus alerts should have Summary and Description.
=> Bug 2012065: Add summary to etcd alert rules

.ci-operator.yaml, Dockerfile.rhel7, go.mod, go.sum
updating #735 with go.mod changes for 1.18.
=> Updating cluster-etcd-operator images to be consistent with ART

bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go
This commit deletes "etcd_perf" files that could present if someone has ran a fio test under /var/lib/etcd
like specified in the OpenShift docs about the recommended host practices.
As this file is known as non essential, it could be freely deleted by anticipation by the restore pod when
restoring a cluster to a previous state.
=> Bug 2087983: remove etcd_perf before restore

manifests/0000_90_etcd-operator_03_prometheusrule.yaml
This PR adds summary to etcd alert rules.
According to [Enhancement](https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#style-guide), all prometheus alerts should have Summary and Description.
=> [release-4.9] Bug 2086119: Add summary to etcd alert rules

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
reverts https://github.com/openshift/cluster-etcd-operator/pull/838/commits/138a12c7e07e98840cb23d1b2708a39a47f6e0e9
=> Bug 2085997: brings back initial delay seconds to the previous value

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
The kubelet uses startup probes to know when a container application has started. Once a probe is configured, it disables liveness and readiness checks until it succeeds.
We give the etcd container a three-minute wait with a 10s startup time minimum (initial delay).
=> Bug 2085997: defines a startupProbe for etcd container

bindata/etcd/cluster-backup.sh, pkg/operator/etcd_assets/bindata.go
As suggested by Thomas, recreating the PR 844, but using the master branch..
-----
I've noticed that the script can be called from the pod cluster-backup-pod.yaml, so kept the test about `${ETCDCTL_CACERT}`, which should work within the pod.
Breaking the script if certificate `${ETCDCTL_CACERT}` is still missing after the variable update.
Tested in one of the quicklab clusters:
~~~
sh-4.4# /usr/local/bin/cluster-backup.sh /home/core/assets/backup
Certificate /etc/kubernetes/static-pod-certs/configmaps/etcd-serving-ca/ca-bundle.crt is missing. Checking in different directory
Certificate /etc/kubernetes/static-pod-resources/etcd-certs/configmaps/etcd-serving-ca/ca-bundle.crt found!
found latest kube-apiserver: /etc/kubernetes/static-pod-resources/kube-apiserver-pod-13
found latest …
=> Bug 2090929: cluster-backup.sh script has a conflict to use the '/etc/kubernetes/static-pod-certs' folder if a custom API certificate is defined

pkg/operator/ceohelpers/common.go, pkg/operator/machinedeletionhooks/machinedeletionhooks.go, pkg/operator/machinedeletionhooks/machinedeletionhooks_test.go
This fixes an issue where a machine can have multiple IPs (dualstack or not doesn't actually matter) and inadvertently removes the deletion hook as not all IPs are returned by the etcd member listing.
The fix is to check if any of the addresses of a machine is still returned from etcd, in such case the machine will remain with the hook. Otherwise we can safely remove the hook for this machine.
=> Bug 2095703: fix multi-address member removal

pkg/operator/ceohelpers/common.go, pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go, pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go
Fix going degraded on missing cluster version. 
As a result of https://github.com/openshift/cluster-etcd-operator/pull/835, the `Backupupgrade` controller while detecting the cluster version, during install and upgrade, raises an error and goes degraded. Such noise is not needed.
=> Bug 2097431: fix degraded missing cluster version

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
This PR adds a liveness probe to etcd pod yaml. 
Currently the etcd cluster considered to be `healthy` if the `etcdctl cluster-health` cmd returns some unhealthy members, while maintaining the quorum. On the other hand, the cmd considers the cluster `unhealthy`, if any of the members is `unreachable`. 
In OCP, we need to detect if a etcd process is not functioning. Currently etcd-container within etcd-pod is being restarted by kubelet when it is not running (e.g. SIGKILL). This PRs adds a liveness probe to detect when etcd process is not functioning (e.g. SIGSTOP).
=> Bug 1884568: Add etcd pod liveness probe

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
This PR removes `etcd-health-monitor` side-car from Etcd Pod manifest. 
During https://github.com/openshift/cluster-etcd-operator/pull/869, we have found out that the `etcd-health-monitor` side car is of no use. Therefore, removing it.
=> remove etcd-health-monitor sidecar from pod manifest

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
From customer on slack: 
I can observe on all OCP 4.10 cluster that the etcd-metrics container is flooding logs with a connection to a port which does not listening on any etcd container.
```
{"level":"info","ts":"2022-06-22T12:59:19.139Z","caller":"zapgrpc/zapgrpc.go:174","msg":"[core] Subchannel picks a new address \"127.0.0.1:23790\" to connect"}
{"level":"warn","ts":"2022-06-22T12:59:19.146Z","caller":"zapgrpc/zapgrpc.go:191","msg":"[core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:23790 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:23790: connect: connection refused\". Reconnecting..."}
```
there's a typo in the pod yaml, with an excessive "s" it uses the default value from: …
=> fixing metrics proxy log spam

bindata/etcd/pod.yaml, cmd/cluster-etcd-operator/main.go, pkg/cmd/readyz/readyz.go, pkg/operator/etcd_assets/bindata.go
This PR adds a liveness and readiness probes to etcd pod manifest.
CherryPick https://github.com/openshift/cluster-etcd-operator/pull/869
=> [release-4.10] Bug 2105249: Add etcd pod liveness and readiness probes

bindata/etcd/cluster-backup.sh, bindata/etcd/etcd-common-tools, pkg/operator/etcd_assets/bindata.go
So cluster-backup.sh exits with non-zero and this return code is usable for monitoring purposes.
=> Exits with a non-zero code in case Etcd backup fails

jsonnet/dashboard.jsonnet, jsonnet/jsonnetfile.lock.json, manifests/0000_20_etcd-operator_00_namespace.yaml, manifests/0000_20_etcd-operator_01_operator.cr.yaml, manifests/0000_20_etcd-operator_02_service.yaml, manifests/0000_20_etcd-operator_03_configmap.yaml, manifests/0000_20_etcd-operator_03_secret.yaml, manifests/0000_20_etcd-operator_04_clusterrolebinding.yaml, manifests/0000_20_etcd-operator_05_serviceaccount.yaml, manifests/0000_20_etcd-operator_10_flowschema.yaml, manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml, manifests/0000_90_etcd-operator_01_prometheusrole.yaml, manifests/0000_90_etcd-operator_02_prometheusrolebinding.yaml, manifests/0000_90_etcd-operator_03_servicemonitor.yaml
This PR removes the grafana etcd-dashboard from Hypershift. 
https://github.com/openshift/cluster-etcd-operator/pull/837 was merged, and it moves the dashboard to CEO, to be removed automatically from Hypershift releases. However, QA identified the dashboard still exist. The annotation `include.release.openshift.io/ibm-cloud-managed` need to be removed from the etcd-dashboard ConfigMap.
=> Bug 2089199: Remove etcd dashboards from Hypershift

pkg/etcdcli/health.go, pkg/etcdenvvar/envvarcontroller.go, pkg/etcdenvvar/etcd_env.go, pkg/etcdenvvar/fake_envvar.go, pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/ceohelpers/control_plane_topology.go, pkg/operator/ceohelpers/qourum_check.go, pkg/operator/ceohelpers/qourum_check_test.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go, pkg/testutils/testutils.go
cherry-pick of 8cd62e65d55c5003dae46b78f835b452b0694889 with fixed imports in starter.go
=> [release-4.10] Bug 2118731: ensure healthy quorum before config update

pkg/etcdcli/health.go
Since you're using resp.Header to get the member ID will likely need to have a check as on line 128 that resp is not nil.
Background saw crash during bootstrap in etcd-operator:
```
I0829 14:46:02.736582       1 controller_manager.go:54] StaticPodStateController controller terminated
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e940ab]
goroutine 2701 [running]:
github.com/openshift/cluster-etcd-operator/pkg/etcdcli.checkSingleMemberHealth({0x29374c0, 0xc00217d920}, 0xc0021fb110)
github.com/openshift/cluster-etcd-operator/pkg/etcdcli/health.go:135 +0x34b
github.com/openshift/cluster-etcd-operator/pkg/etcdcli.getMemberHealth.func1()
github.com/openshift/cluster-etcd-operator/pkg/etcdcli/health.go:58 …
```
=> OCPBUGS-675: add nil check in checkSingleMemberHealth()

pkg/etcdcli/health.go
It's actually silly to take the member id from the response header when we know exactly which client url we're talking to in the first place.
=> OCPBUGS-675: preserve log message on failures

OWNERS
backport of https://github.com/openshift/cluster-etcd-operator/pull/818
=> [release-4.8] OCPBUGS-1307: backport owners

pkg/operator/ceohelpers/common.go, pkg/operator/machinedeletionhooks/machinedeletionhooks.go, pkg/operator/machinedeletionhooks/machinedeletionhooks_test.go, pkg/operator/starter.go
Opening this to start a discussion.
I've been working on the ControlPlaneMachineSet and trying to automate replacement of the Control Plane Machines using our on-delete strategy.
One of the things we expect to be able to do is to create multiple replacement machines simultaneously (when a user deletes multiple machines simultaneously) and have the etcd operator handle moving etcd onto the new machines in quick succession.
This seems to work well!
However, what doesn't work currently is that the quorum guard on the old machines ends up failing, members that have been removed from the etcd cluster fail the health check. This means you now have multiple failing quorum guard pods.
The PDB blocks these from being removed.
To avoid this, we can be remove the quorum guard pod from a machine that …
=> Remove quorum guard pod after the pod is removed from the cluster

jsonnet/custom.libsonnet, jsonnet/jsonnetfile.lock.json, jsonnet/main.jsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
This replaces the upstream alert with something that's a lot less sensitive to bad etcd (fsync) latency.
=> OCPBUGS-1130: increase etcdGRPCRequestsSlow thresholds

manifests/0000_90_etcd-operator_03_prometheusrule.yaml
This never had any targets in Hypershift so it is pointless. Since
b4537b9f59077fddfcbb3bc6e75021376040b715 it started to cause errors,
because the namespace isn't applied anymore:
```
- lastTransitionTime: "2022-08-26T17:09:57Z"
message: 'Could not update prometheusrule "openshift-etcd-operator/etcd-prometheus-rules"
(537 of 566): resource may have been deleted'
```
We currently worked around this in Hypershift itself by deleting that
manifest, but that is not a great solution: https://github.com/openshift/hypershift/pull/1699/commits/2c927d9985059ddb3ad26332e088dcd2286ba94e
/assign Elbehery
/cc @tjungblu
=> Hypershift: Stop trying to apply etcd prometheusrule

pkg/etcdcli/etcdcli.go, pkg/etcdcli/etcdcli_test.go, pkg/etcdcli/helpers.go, pkg/etcdcli/interfaces.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go, pkg/testutils/testutils.go
Currently the clustermemberremoval controller will automatically remove an etcd member when the pre-conditions for scale down are met, i.e we have a machine pending deletion and N+1 voting members where N is the desired control-plane size.
However, if we have the scaling down conditions met, but the etcd cluster is unhealthy (i.e. unhealthy voting member found), 
clustermemberremoval will not attempt to scale down. 
This PR relaxes the scaling down condition, which allows clustermemberremoval to remove unhealthy voting member, if the current voting members count is N+1, while N is the `desiredControlPlaneReplicaCount`.
=> OCPBUGS-1000: Allow scale-down of unhealthy member

docs/performance-metrics.md
I noticed I got a few metrics wrong today while debugging a ci failure using promecleus.
=> doc fixes for prometheus metrics

pkg/etcdcli/health.go, pkg/etcdcli/health_test.go, pkg/operator/ceohelpers/common.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
This PR attempts to allow replacing an unhealthy etcd member from the cluster, with a replacement as learner. It relaxes the scaling down invariant to the minimum tolerable threshold in order to maintain Quorum.
=> ETCD-328: automatic replacement of an unhealthy member machine

pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller_test.go, pkg/testutils/testutils.go
including the tests from https://github.com/openshift/cluster-etcd-operator/pull/955
=> OCPBUGS-4193: later bootstrap removal in delayed scaling

bindata/etcd/pod.yaml, pkg/cmd/readyz/readyz.go, pkg/operator/etcd_assets/bindata.go
manually verified with clusterbot and drwetter/testssl.sh it's not vulnerable anymore:
for port 9979:
```
Testing vulnerabilities 
Heartbleed (CVE-2014-0160)                not vulnerable (OK), no heartbeat extension
CCS (CVE-2014-0224)                       not vulnerable (OK)
Ticketbleed (CVE-2016-9244), experiment.  not vulnerable (OK), no session tickets
ROBOT                                     Server does not support any cipher suites that use RSA key transport
Secure Renegotiation (RFC 5746)           supported (OK)
Secure Client-Initiated Renegotiation     client x509-based authentication prevents this from being tested
CRIME, TLS (CVE-2012-4929)                not vulnerable (OK)
BREACH (CVE-2013-3587)                    client x509-based authentication prevents this from being …
```
=> OCPBUGS-1123: only allow TLS1.2/1.3 ciphersuites in etcd and CEO

pkg/operator/defragcontroller/defragcontroller.go
The typo snuck into logs with the initial controller implementation in 4a197b0d2c (#625).
=> pkg/operator/defragcontroller: Fix "stabalize" -> "stabilize" typo

pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go
From [the API docs][1]:
> reason is the CamelCase reason for the condition's current status.
This change will get us `EtcdMembers_NoQuorum` instead of the current `EtcdMembers_No quorum`
[1]: https://github.com/openshift/api/blob/cce310ad2932f6de24491052d506926e484c082c/config/v1/types_cluster_operator.go#L131-L133
=> pkg/operator/etcdmemberscontroller: Slugify "No quorum" to "NoQuorum"

pkg/cmd/verify/backupstorage.go, pkg/etcdcli/etcdcli.go, pkg/etcdcli/etcdcli_pool.go
The ceo operator connect to etcd without timeout, which may lead to some ceo controllers(like EtcdEndpointsController, EtcdCertSignerController and so on ) may be stuck in etcd member list interface about 15minutes, which finally may be closed by the operating system after 15 minutes
[issue1000: fix ceo connection timeout ](https://github.com/openshift/cluster-etcd-operator/issues/1000)
1. this problem can be reproduced by rm one master node, and the pprof top info will show like this:
2. maybe the 60s is not suitable for most conditions，we can discuss about this
Signed-off-by: lan.tian <lance5890@163.com>
=> OCPBUGS-7374: set default timeouts in etcdcli

docs/etcd-tls-assets.md
1. The Prune func are general methods for all static pod(like  kube-apiserver,  kube-controller-manager, kube-scheduler, etcd)
2. But in the ceo docs, the description should  be used for cluster-etcd-operator as an example, to avoid misleading
=> document adaptation with ceo

docs/HACKING.md
This PR documents how CEO uses `release.openshift.io/delete: "true"` annotation to garbage collect resources
e.g. https://github.com/openshift/cluster-etcd-operator/pull/1016
=> add resource removal by CVO

bindata/etcd/cluster-restore.sh, pkg/etcdcli/etcdcli.go, pkg/operator/etcd_assets/bindata.go
in order to do a simple restore from snapshot you can run this:
> [root@ci-ln-z11m7db-72292-s28sd-master-1 tmp]# export ETCD_RESTORE_SKIP_MOVE_CP_STATIC_PODS=true
> [root@ci-ln-z11m7db-72292-s28sd-master-1 tmp]# export ETCD_ETCDCTL_RESTORE=true
> [root@ci-ln-z11m7db-72292-s28sd-master-1 tmp]# ./cluster-restore.sh
recreated as #1041 has its label stuck
=> OCPBUGS-14254: Restore script improvements

pkg/operator/clustermembercontroller/clustermembercontroller.go
resolves https://issues.redhat.com/browse/OCPBUGS-14296
=> OCPBUGS-14296: skip unstartedEtcdMember event

manifests/image-references
[remove unused cli image issue 1052](https://github.com/openshift/cluster-etcd-operator/issues/1052)
=> Remove unused cli docker image

manifests/0000_20_etcd-operator_06_deployment.yaml
[issue 1061](https://github.com/openshift/cluster-etcd-operator/issues/1061)
=> manifests: bump loglevel of operator to normal

jsonnet/jsonnetfile.lock.json, jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet, jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
Limiting alerting of higher percentages in small databases should improve how actionable the alert will be and is present in upstream: https://github.com/etcd-io/etcd/commit/1002346ceb37f1b097d52d72823a1ab7401bfd52
=> [OSD-16903] Limit etcdDatabaseHighFragmentationRatio to 100MB+

bindata/etcd/cluster-backup.sh, bindata/etcd/cluster-restore.sh, bindata/etcd/etcd-common-tools, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go
This PR will:
* use etcdutl when available, to ease the eventual transition towards 3.6 
* add a rev bump by 1 billion and mark compacted to test the feature in our CI restore job, flagged off by default
=> add rev bumps and etcdutl

pkg/operator/health/aliveness_checker.go
Turns out that debug.PrintStack only outputs the current stack, which is kubelet scraping the /healthz endpoint. Not exactly helpful when trying to figure out where something is stuck on. 
There's another utility to dump all goroutines in the runtime package, which has a boolean parameter "all".
=> dump all goroutines, not the current stack

pkg/operator/ceohelpers/machine_api.go, pkg/operator/ceohelpers/machine_api_test.go
turns out "None" is not easy to depend on, when running an installation with the flags customized you can set different baselines:
```
spec:
capabilities:
baselineCapabilitySet: v4.13
channel: stable-4.14
status:
availableUpdates: null
capabilities:
enabledCapabilities:
- CSISnapshot
- Console
- Insights
- NodeTuning
- Storage
- baremetal
- marketplace
- openshift-samples
```
This PR removes the None check entirely and relies on the status fields.
=> OCPBUGS-16889: machine api check: rely on status more than baseline

pkg/operator/backupcontroller/backupcontroller.go, pkg/operator/backupcontroller/backupcontroller_test.go, test/e2e/backup_test.go
When we create a backup for a pvc that doesn't exist the pod will just be stuck in Pending state forever. This PR introduces validation for it and marks the backup as failed before spawning a pod.
=> add pvc validation and e2e tests

bindata/etcd/etcd-common-tools, pkg/operator/etcd_assets/bindata.go
the auth file seems used as a command argument to the container creation instead of a podman option.
=> OCPBUGS-18357: prepend authfile to podman create

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
This PR bumps library-go to get the latest static pod permissions(more specifically https://github.com/openshift/library-go/pull/1576).
=> [release-4.14] OCPBUGS-19553: Update static pod manifests perms

pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
Reverts openshift/cluster-etcd-operator#1151
to be compared with #1165 for AI issues
/hold
=> Revert "[release-4.13] OCPBUGS-23044: remove revision stability check from bootstrap complet…"

bindata/bootkube/manifests/etcd-ca-bundle-configmap.yaml
This is input from the installer, but its not user provided so it is logically owned by the component
=> add ownership for etcd-ca-bundle that I don't think is updated

bindata/etcd/cluster-backup-pod.yaml, pkg/operator/etcd_assets/bindata.go
In some file system implementations the root dir can't be removed itself when mounted. This fix will only delete all contents of the directory.
=> OCPBUGS-26214: fix device busy errors

docs/etcd-tls-assets.md, go.mod, go.sum, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/resourcesynccontroller/resourcesynccontroller.go, pkg/tlshelpers/tlshelpers.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go, vendor/modules.txt
This PR will
* replace the existing cert rotation logic with more battle tested ones from library-go
* create new signer certificates (metrics + serving) in openshift-etcd namespace, in addition to existing ones in openshift-config
* create new server certificates (peer, serving, serving-metrics)
* create new client certificates (etcd-client, etcd-metrics)
* bundle existing signer certificates with newly created CAs (to stay backward compatible)
The consequence of merging this PR is:
* an additional static pod rollout during installation and upgrades (slightly longer install/upgrade time expected)
* all existing certs are rotated with existing old and new signers, which are distributed to all nodes for actual signer rotation later on
=> ETCD-512: refactoring the cert signer controller

manifests/0000_20_etcd-operator_10_flowschema.yaml
Reverts openshift/cluster-etcd-operator#1197
entirely unrelated to #1194 - PEBCAK 
/hold
until we get the cert changes in however.
=> Revert "Revert "OCPBUGS-22969: Use v1 for flowcontrol API""

pkg/etcdcli/etcdcli_pool.go
recent profiling determined that CEO is constantly exhausting the clients in the pool - wasting precious CPU cycles on TLS handshakes. This increases the amount of cached clients to 10, peak to 20 to ensure better cache hit rates.
=> NO-JIRA: increase client pool size

go.mod, go.sum, pkg/tlshelpers/tlshelpers.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/metadata.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go, vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go, vendor/modules.txt
Syncing with https://github.com/openshift/library-go/pull/1682
=> WRKLDS-1071: bump(library-go)=master

pkg/etcdenvvar/envvarcontroller.go, pkg/etcdenvvar/envvarcontroller_test.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/configobservation/configobservercontroller/observe_config_controller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
From profiling on cert rotation we know that the node informer is called every couple of seconds on node heartbeats. This PR will ensure that all our node listers only ever listen/inform on the master node updates to reduce the frequency of unnecessary sync calls.
=> OCPBUGS-30245: [4.13] Replace nodelister with master nodelister everywhere

pkg/operator/health/aliveness_checker.go, pkg/operator/health/checking_sync_wrapper.go, pkg/operator/health/checking_sync_wrapper_test.go
Currently we only detect whether a controller has been running continuously into errors. Whereas we wanted to detect real deadlock situations. This change defuses the aliveness check to only declare real locking situations as problematic.
Additionally, to not create insane amounts of log traffic, this change will throttle the stack dumping to once every 15 minutes. Previously it would trigger almost immediately every health probe invocation and create multi-megabyte log spam.
=> OCPBUGS-30873: CEO aliveness check should only detect deadlocks

pkg/etcdcli/etcdcli.go, pkg/etcdcli/etcdcli_opts.go
Reverts openshift/cluster-etcd-operator#1215
=> Revert "OCPBUGS-30169: add timeout to etcd client.New config"

go.mod, go.sum, pkg/tlshelpers/target_cert_creator.go, pkg/tlshelpers/target_cert_creator_test.go, pkg/tlshelpers/tlshelpers.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/annotations.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go, vendor/modules.txt
/hold
The cool thing is that we're now able to "swap" signers with the existing logic with:
> $ oc get secret etcd-signer -n openshift-etcd -ojson | jq 'del(.metadata["namespace","creationTimestamp","resourceVersion","selfLink","uid"])' | oc apply -n openshift-config -f -
which is effectively overwriting the new signer from `openshift-etcd` into the old signer in `openshift-config`. That works, because the bundle with the new signer is already distributed to all CP nodes. CEO will then proceed to rewrite all leaf certs, which are then rolled out together via `etcd-all-certs`. 
Manual rotation is then just two step manual process:
Generate new signer: 
>  $ oc delete secret etcd-signer -n openshift-etcd
... wait for the rollout ...
Replace the old signer with the new signer:
> $ oc get …
=> ETCD-535: Manual CA rotation should rotate all leaf certs

pkg/tlshelpers/tlshelpers.go
Addresses https://issues.redhat.com/browse/ETCD-580 to leave enough time on the cert before it is expired in the event the cluster is shutdown/hibernated for 9 months.
This helps prevent etcd certs from becoming expired while the cluster is offline for extended periods. 
/cc @tjungblu
=> ETCD-580: Decrease validity period to prevent cert expiry for offline clusters

pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/ceohelpers/bootstrap.go, vendor/github.com/openshift/library-go/pkg/operator/bootstrap/bootstrap.go, vendor/modules.txt
The function was copied form this operator and moved to library-go in https://github.com/openshift/library-go/pull/1714.
This PR simply uses the function from the library-go
=> NO-ISSUE: use IsBootstrapComplete from library-go

manifests/0000_20_etcd-operator_03_secret.yaml
SecretTypeTLS is a deprecated type, which gets converted to kubernetes.io/tls when controller parses. Changing this type to supported to make controller skip convertion on initial install.
Ref: https://issues.redhat.com/browse/API-1800
=> API-1800: manifests: convert SecretTypeTLS secrets to kubernetes.io/tls

pkg/cmd/waitforceo/waitforceo.go, pkg/operator/bootstrapteardown/waitforceo.go
Fixes [OCPBUGS-33495](https://issues.redhat.com/browse/OCPBUGS-33495) as we were swallowing errors in the wait-for-ceo cmd
/cc @dusk125 @tjungblu
=> OCPBUGS-33495: return errors in wait-for-ceo

pkg/operator/targetconfigcontroller/targetconfigcontroller.go
1. similar to the https://github.com/openshift/cluster-etcd-operator/pull/1239, I found the ceo could also rollout when remove one master node
2. the targetconfigcontroller  should check the cluster is safe or not when get env vars, in case the env vas have changed, but the cluster is not healthy yet
=> NO-JIRA:check the cluster is healthy or not after getting env var, to ensure it is safe to rollout

pkg/operator/ceohelpers/common.go, pkg/operator/ceohelpers/common_test.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Salvage from the previous reverted PR we had in 4.16. Note that some of those helpers are not actively used yet, but it's used in a follow-up PR.
=> ETCD-603: add revision helpers

bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/cmd/render/certs_test.go, pkg/etcdenvvar/envvarcontroller_test.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/starter.go, pkg/tlshelpers/tlshelpers.go
This PR creates a new "etcd-all-bundles" configmap, similar to "etcd-all-certs", which allows us to transactionally create static pod rollouts on bundle changes.
This is a pre-requisite to allow us to gate leaf certificate changes right after a bundle changes.
--
The TODOs are expected to not have TRT revert weeks-worth of pull request work, this will not change the existing behavior. A follow-up PR will update the CEO status to reflect the changed revision and documentation.
=> ETCD-606: Batch bundle revision rollout

bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/cmd/render/certs_test.go, pkg/etcdenvvar/envvarcontroller_test.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/starter.go, pkg/tlshelpers/tlshelpers.go
Reverts #1268 ; tracked by https://issues.redhat.com/browse/TRT-1687
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.
Appear to be intermittently failing a pathological event test enough to take out 4.17 CI payloads
To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:
```
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-aws-ovn-upgrade 10
```
CC: @tjungblu
<div align="right">
PR …
=> TRT-1687: Revert #1268 "ETCD-606: Batch bundle revision rollout"

pkg/cmd/render/certs_test.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/testutils/testutils.go
we have been using different, but similar assertions for the cert rotation in render and the controller. The render assertions were much stronger, so I've added them into testutils and to the controller tests.
=> NO-JIRA: cert rotation same assertions

pkg/etcdcli/etcdcli.go, pkg/etcdcli/health.go
Currently, member health is checked in serial with a 30s timeout per member. 3 out of 4 GetMemberHealth callers had their own default 30s timeout as well for the entire process. Because of this, a slow check on one member could exhaust the timeout for the entire GetMemberHealth function, and thus cause later-checked members to report as unhealthy even though they were fine.
With this commit, I am dropping the internal 30s timeout from GetMemberHealth, and instead letting the caller set the timeout. Also, the code now checks the health of all members in parallel. This will prevent a single slow member from affecting the health reporting of other members.
I also added a timeout to the context used in IsMemberHealthy which calls GetMemberHealth. Neither Trevor nor I were sure why a default …
=> OCPBUGS-36301: parallelize member health checks

manifests/0000_20_etcd-operator_03_configmap.yaml
This should avoid cases where the static pod installer controller races with the cert controller and they would block each other on that resource.
=> OCPBUGS-36621: add etcd-all-bundles to cvo create-only

docs/etcd-tls-assets.md, pkg/cmd/render/certs_test.go, pkg/operator/resourcesynccontroller/resourcesynccontroller.go
This cleans up some certificates that were copied but are not longer needed. At the same time, updating the docs to the state of today.
=> ETCD-604: Prune revisioned resources

pkg/cmd/prune-backups/prune.go, pkg/cmd/prune-backups/prune_test.go
This PR exposes `pruneOpts` struct.
This is part of https://issues.redhat.com/browse/ETCD-636 
cc @openshift/openshift-team-etcd
=> ETCD-636: expose PruneOpts

pkg/etcdenvvar/envvarcontroller.go
While reviewing the changes in the backup PR, I've seen that I've introduced unnecessary listener updates during the lock refactoring two years ago.
This PR ensures we return early when the envvars has not changed.
=> NO-JIRA: only update envvar listeners on real changes

pkg/etcdcli/health.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
Changes in the health check caused equality checks during member removal to result in incorrect vertical scaling behavior.
=> OCPBUGS-36462: ensure ordering in member health checks

pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
This is a more general refactoring to degrade the whole controller when quorum is lost. This should make it easier to assert in e2e tests and is more consistent with the behavior in the other controllers.
=> NO-JIRA: degrade targetconfigcontroller on quorum loss

bindata/etcd/pod.yaml, pkg/cmd/readyz/readyz.go, pkg/operator/etcd_assets/bindata.go
This rectifies the hardcoding of the ciphers that I've introduced in #970, which is shadowing the ciphers set through the etcd cluster CRD.
=> OCPBUGS-38341: prefer env var over hardcoding ciphers

pkg/etcdcli/etcdcli.go, pkg/etcdcli/health.go
This should reduce CPU consumption because of less TLS handshakes and makes it usable from other places too.
=> OCPBUGS-38573: use pooled client for etcd single member health checks

pkg/etcdcli/etcdcli.go, pkg/etcdcli/health.go
Reverts openshift/cluster-etcd-operator#1319
not sure this is working as expected, I see many logs like this now:
> [etcd-operator-78ddbd8998-r7f4t] W0821 08:54:24.113978       1 etcdcli_pool.go:87] cached client detected change in endpoints [[https://10.0.0.5:2379]] vs. [[https://10.0.0.3:2379 https://10.0.0.4:2379 https://10.0.0.5:2379]]
and then subsequently the controllers picking up the client is not using the right endpoints anymore:
> [etcd-operator-78ddbd8998-r7f4t] E0821 09:05:44.532054       1 base_controller.go:268] DefragController reconciliation failed: failed to dial endpoint https://10.0.0.4:2379 with maintenance client: context deadline exceeded
/hold
=> Revert "OCPBUGS-38573: use pooled client for etcd single member health checks"

bindata/etcd/pod.yaml, cmd/cluster-etcd-operator/main.go, pkg/cmd/backuprestore/backupserver.go, pkg/operator/etcd_assets/bindata.go
This PR adds `etcd-backup-server` sidecar skeleton.
This is part of https://issues.redhat.com/browse/ETCD-636
cc @openshift/openshift-team-etcd
=> ETCD-659: Add `etcd-backup-server` sidecar skeleton

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
This PR removes the executable bit from etcd log's permission. 
see https://github.com/openshift/cluster-etcd-operator/pull/1306#discussion_r1747217442
=> NO-JIRA: fix log folder permission

pkg/cmd/rev/rev.go, pkg/cmd/rev/rev_test.go
This is required because the cluster id is not stored in the raft hardstate. It proved difficult to re-generate this from within the initial cluster discovery binary based on environment variables, so we're storing it more explicitly in the revision.json.
This also fixes a flake when the leader is terminated in the unit tests.
requirement for https://github.com/openshift/etcd/pull/284
=> ETCD-656: add cluster identifier to revision.json

bindata/etcd/cluster-restore.sh, bindata/etcd/etcd-common-tools, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go
This updates the restore script and pod to take advantage of the revision file introduced in a previous PR.
/hold
=> ETCD-653: Update restore-pod to use locally stored revision

bindata/etcd/pod.gotpl.yaml, pkg/backuphelpers/backupvars.go, pkg/backuphelpers/backupvars_test.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
This moves the pod.yaml to a go templated one, with all values replaced by a proper templating engine intead of string replacement.
=> ETCD-678: introduce a templated pod.yaml

bindata/etcd/pod.gotpl.yaml, bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/periodicbackupcontroller/periodicbackupcontroller.go, pkg/operator/periodicbackupcontroller/periodicbackupcontroller_test.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go, pkg/testutils/testutils.go
This PR removes `etcd-backup-server` based on StaticPod. 
The `StaticPod` approach has been replaced by https://github.com/openshift/cluster-etcd-operator/pull/1354 
Comparing against 4.17 branch [link](https://github.com/openshift/cluster-etcd-operator/compare/release-4.17...Elbehery:remove_etcd-backup-server_staticPod)
resolves https://issues.redhat.com/browse/ETCD-686 
cc @openshift/openshift-team-etcd
=> ETCD-686: Remove etcd-backup-server StaticPod approach

pkg/operator/starter.go
This one is using JSON instead of protobuf
=> OCPBUGS-43920: operator: remove duplicate kube client

pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go
Separated the revision stability check from the bootstrap completeness check to ensure the revision stability check is only called from controllers that need them.
=> OCPBUGS-17199: Separated the revision stability check from the bootstrap completeness check

bindata/etcd/pod.gotpl.yaml, pkg/cmd/readyz/readyz.go, pkg/etcdenvvar/envvarcontroller_test.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
- **add ETCD_TLS_MIN_VERSION env to etcd pods**
- **add listen-tls-min-version flag to readyz cmd**
- **do not start etcd with --cipher-suites with tls1.3**
=> OCPBUGS-43748: etcd pod containers do not start when tls min version is 1.3

bindata/etcd/pod.gotpl.yaml, pkg/operator/ceohelpers/unsupported_override.go, pkg/operator/ceohelpers/unsupported_override_test.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
/hold
for testing purposes in 2NO
=> ETCD-677: add unsupported config override for etcd container removal

pkg/cmd/backuprestore/backupserver_test.go
This PR fixes `TestNewBackupServer_scheduleBackup` due to changes in go1.23 `ticker` implementation.
Changes that caused the issue
```
Second, the timer channel associated with a Timer or Ticker is now unbuffered, with capacity 0. The main effect of this change is that Go now guarantees that for any call to a Reset or Stop method, no stale values prepared before that call will be sent or received after the call. Earlier versions of Go used channels with a one-element buffer, making it difficult to use Reset and Stop correctly. A visible effect of this change is that len and cap of timer channels now returns 0 instead of 1, which may affect programs that poll the length to decide whether a receive on the timer channel will succeed. Such code should use a non-blocking receive instead.
```
=> NO-JIRA: fix schedule backup test

pkg/etcdcli/etcdcli.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller_test.go
This generates an event upon successful bootstrap member removal 
see https://issues.redhat.com/browse/OCPBUGS-48400
=> OCPBUGS-48400: generate event upon successfull bootstrap member removal

test/e2e/etcdctl_test.go
Most of `etcdctl` [e2e](https://github.com/openshift/cluster-etcd-operator/blob/c956ac315dddcb510a1f4ca75fe7a0fdf8569711/test/e2e/etcdctl_test.go#L18)  test are disabled by default.
During last weeks, this test has failed most of the time, from changes that is non related to it. 
It is better to disable it, as it blocks more important work, for no reason. 
cc @tjungblu
=> NO-JIRA: restrict `etcdctl defrag` to single member

bindata/etcd/external-etcd-pod-cm.yaml, pkg/dualreplicahelpers/dual_replica_helpers.go, pkg/dualreplicahelpers/dual_replica_helpers_test.go, pkg/operator/ceohelpers/control_plane_topology.go, pkg/operator/ceohelpers/podsubstitution.go, pkg/operator/ceohelpers/unsupported_override.go, pkg/operator/ceohelpers/unsupported_override_test.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/externaletcdsupportcontroller/external_etcd_support_controller.go, pkg/operator/externaletcdsupportcontroller/external_etcd_support_controller_test.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
The _EnableEtcdContainer unsupported config override_ removes the etcd container from the static pod definition when set to FALSE.
This change extends that behavior by writing a separate Pod definition containing **only** the etcd container, using the same source from which it was removed, but placing it in a location that does not trigger pod creation.
This allows an external etcd manager to run etcd independently while ensuring it has a reliable source for updates from CEO (e.g., new image, path to certificates, etc.).
=> OCPEDGE-1498: support updates to external etcd

jsonnet/custom.libsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
This PR bumps the `etcdGRPCRequestsSlow` alert duration from `30m` to `60m`.
fixes https://issues.redhat.com/browse/OCPBUGS-54222.
=> OCPBUGS-54222: increase etcdGRPCRequestsSlow duration

pkg/operator/configobservation/controlplanereplicascount/observe_control_plane_replicas_count.go
When using TNA clusters, the observedConfig.controlPlane.replicas needs to include the arbiter nodes.
Currently it uses an incorrect field to get the number of arbiter nodes - it uses `arbiterNode` but the actual field is called `arbiter`.
=> OCPEDGE-1773: Fix arbiter field in install-config

pkg/tnf/pkg/pcs/etcd.go
Specifying 'meta' after 'clone' defines meta attributes for the base resource, not for the clone as the agent needs for the "notify=true" meta attribute.
See: https://bugzilla.redhat.com/show_bug.cgi?id=2168155
Fixes: OCPBUGS-55111
=> OCPBUGS-55111: Remove 'meta' keyword from pcs resource create command

bindata/tnfdeployment/aftersetupjob.yaml, bindata/tnfdeployment/authjob.yaml, bindata/tnfdeployment/setupjob.yaml, pkg/tnf/assets/bindata.go
- remove resource limits
- add priorityClass
Note: I will consider to have 1 job manifest for all TNF jobs, and set the actual name and command dynamically, in order to reduce duplication. Since this is going to be backported to 4.19, I keep the change small here.
=> OCPEDGE-1920: Comply with OCP pod standards for TNF jobs

pkg/tnf/pkg/pcs/etcd.go
Use the podman-etcd agent installed by the `two-node-ha` extension instead of the one installed by MCO/RHCOS symlink
=> CNTRLPLANE-806: Explicitly use podman-etcd from two-node-ha extension

pkg/tnf/operator/starter.go, pkg/tnf/pkg/config/cluster.go, pkg/tnf/pkg/config/cluster_test.go
When being installed with assisted installer, the 1st auth job  is already created when 1 cp node is available only. Wait with the job creation until both nodes exist, ensure jobs are created once only, and double check node count inside jobs.
=> OCPBUGS-57372: Wait for 2 cp nodes before starting TNF jobs

bindata/etcd/pod.gotpl.yaml, bindata/etcd/svc.yaml, pkg/operator/etcd_assets/bindata.go
To help with the commatrix project, we were asked to document the ports that we expose to the outside world. This adds the missing ports to the service and the respective container.
Note that container ports on pod specs are just informational, they do not expose/block access.
=> OCPBUGS-50488: add missing ports to svc and pod spec

pkg/tnf/pkg/pcs/fencing.go, pkg/tnf/pkg/pcs/fencing_test.go
see https://access.redhat.com/solutions/54829
=> OCPEDGE-1998: TNF: Use `pcmk_delay_base` on 1st fence device to prevent fencing races

pkg/tnf/pkg/jobs/jobcontroller_test.go
These tests were added for moving the controller to library-go, which won't happen though, so let's add the tests here. Tests are similar to [DeploymentController](https://github.com/openshift/library-go/blob/master/pkg/operator/deploymentcontroller/deployment_controller_test.go) tests. Also, they are AI generated.
=> NO-JIRA: Add more unit tests for JobController

jsonnet/custom.libsonnet, jsonnet/jsonnetfile.lock.json, jsonnet/main.jsonnet, jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/alerts/alerts.libsonnet, jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml, jsonnet/vendor/github.com/jsonnet-libs/xtd/ascii.libsonnet, jsonnet/vendor/github.com/jsonnet-libs/xtd/docs/ascii.md, jsonnet/vendor/github.com/jsonnet-libs/xtd/docs/inspect.md, jsonnet/vendor/github.com/jsonnet-libs/xtd/inspect.libsonnet, jsonnet/vendor/github.com/jsonnet-libs/xtd/test/inspect_test.jsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
This PR introduces a few changes, primarily in motivation of resolving [OCPBUGS-60237](https://issues.redhat.com/browse/OCPBUGS-60237). **Note** this is the second attempt at these changes, as the previous attempt was reverted due to CI issues.
The following "housekeeping" changes:
- Vendor the latest `etcd-mixin` changes. This includes overwriting some previous manual modifications introduced in https://github.com/openshift/cluster-etcd-operator/commit/674ff5490cb98a38a6d216bf8228e9e58eca085d.
- In support of the above, redefine `etcdHighCommitDurations` to have a threshold of `>0.5` to deal with slow Azure disks vs special casing the platform.
- Redefine `etcdMembersDown` in our custom rules. This rule was changed to a `warning` severity, and the `for` to 20m. Per conversation with …
=> OCPBUGS-60237: Vendor latest mixin, including additional and modified alerts for etcdDatabaseQuotaLowSpace

pkg/etcdcli/health.go
When one member is timing out, the others were also declared unhealthy due to the shared timeout being cancelled.
This adds a new context with an individual timeout to each member health check.
With this fix only the respective member is being considered unhealthy:
```
[etcd-operator-566ff8dd4-dn5qx] E0828 11:20:04.415537       1 health.go:120] health check for member (tjungblu15-dq6nb-master-0) failed: err(context deadline exceeded)
[etcd-operator-566ff8dd4-dn5qx] W0828 11:20:04.415708       1 etcdcli.go:356] UnhealthyEtcdMember found: [tjungblu15-dq6nb-master-0]
...
[etcd-operator-566ff8dd4-dn5qx] E0828 11:21:01.300834       1 base_controller.go:279] "Unhandled Error" err="DefragController reconciliation failed: cluster is unhealthy: 2 of 3 members are available, …
```
=> OCPBUGS-60941: add individual context to the health check

bindata/etcd/cluster-restore.sh, bindata/etcd/disable-etcd.sh, bindata/etcd/quorum-restore.sh, pkg/operator/periodicbackupcontroller/periodicbackupcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go
As we use `disable-etcd.sh` to disable etcd , it shows as 
```
...stopping etcd-pod.yaml
Waiting for container etcd to stop
.complete
Waiting for container etcdctl to stop
............................complete
Waiting for container etcd-metrics to stop
complete
Waiting for container etcd-readyz to stop
complete
Waiting for container etcd-rev to stop
complete
Waiting for container etcd-backup-server to stop
complete
```
However, the `etcd-backup-server` is not existed in the static pods, which is removed by https://github.com/openshift/cluster-etcd-operator/pull/1358
=> NO-JIRA: remove etcd-backup-server from static pod lists
