openshift/cluster-etcd-operator

Makefile, README.md
=> *: update operator boilerplate to reflect proper naming

manifests/0000_12_etcd-operator_00_namespace.yaml, manifests/0000_12_etcd-operator_01_config.crd.yaml, manifests/0000_12_etcd-operator_02_service.yaml, manifests/0000_12_etcd-operator_03_configmap.yaml, manifests/0000_12_etcd-operator_04_clusterrolebinding.yaml, manifests/0000_12_etcd-operator_05_serviceaccount.yaml, manifests/0000_12_etcd-operator_06_deployment.yaml, manifests/0000_12_etcd-operator_07_clusteroperator.yaml, manifests/0000_90_etcd-operator_01_prometheusrole.yaml, manifests/0000_90_etcd-operator_02_prometheusrolebinding.yaml, manifests/0000_90_etcd-operator_03_servicemonitor.yaml
Adds manifests for installation
=> Add manifests for installation

OWNERS, glide.lock, glide.yaml
=> OWNERS: add hexfusion

Dockerfile, Dockerfile.rhel7
=> Dockerfile: remove from CVO operator payload

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
Before this fix every time the reconciliation loop ran, secret data
was updated, which was not ideal
=> pkg/operator/etcdcertsigner: this fix only updates secret if empty

pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/clustermembercontroller/clustermembercontroller_test.go, pkg/operator/configobservation/configobservercontroller/observe_config_controller.go, pkg/operator/configobservation/etcd/observe_etcd.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/hostetcdendpointcontroller/hostendpointcontroller.go, pkg/operator/hostetcdendpointcontroller/hostendpointcontroller_test.go
- added fix to set Degraded status so bootstrap teardown works
- added storageURLs back
- fix observe_etcd to take ip address for etcd-bootstrap
=> *: minor changes to bootstrap successfully

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, pkg/cmd/render/options/config.go, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
This PR adds the start of IPv6 support for the operator.
Also added issue to track missing  tests https://github.com/openshift/cluster-etcd-operator/issues/43
=> render: add support for parsing SDN CIDR

pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/clustermembercontroller/clustermembercontroller_test.go
=> clustermembercontroller: fix incorrect error reporting during bootstrap

pkg/cmd/staticpodcontroller/staticpodcontroller.go
mco prevents go mod from working and this removes the one dep
=> bug 1798219: use dynamic client instead of taking an MCO dependency

pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/bootstrapteardown/waitforceo.go, pkg/operator/clustermembercontroller/clustermembercontroller.go
=> bug 1798582: *: fixups: remove unmanaged in waitforceo.go, fix typo

pkg/cmd/staticpodcontroller/staticpodcontroller.go, pkg/cmd/staticsynccontroller/staticsynccontroller.go, pkg/operator/bootstrapteardown/waitforceo.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/hostetcdendpointcontroller/hostendpointcontroller.go
Remove any obedience of being `Unmanaged`. We are always `Managed`.
=> Bug 1798586: pkg/*: Remove support for Unmanaged

pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/hostetcdendpointcontroller/members.go
New etcd clients that use gRPC 1.23+ require the use of `grpc.WithBlock()`or connection can close before call is made.
Also bumping timeout to use apiserver default and explicitly calling cancel() on ctx after every call.
=> Bug 1800810: pkg/operator/clustermembercontroller: add WithBlock() to dial options

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/etcdcertsigner2/etcdcertsignercontroller.go, pkg/operator/resourcesynccontroller/resourcesynccontroller.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/etcd_env.go
This wires our secrets and env vars to our etcd process
=> bug 1800313: the etcd process 

pkg/operator/hostendpointscontroller/host_endpoints_controller.go
We sort the endpoint address slice within an endpoint subset in order to avoid hot-looping if the order of the items in the slice changes.
Upon updating an endpoint, the previous order of the endpoint address in the  slice is preserved if they are unchanged, regardless of the order presented on update.
Ensure that differences in only the order of endpoint addresses do not cause hot-looping.
=> bug 1802245: fix host endpoint hotloop

pkg/operator/etcdcertsigner2/etcdcertsignercontroller.go
found a bug.  We were fighting over the value of some secrets
=> bug 1802578: fix the etcd serving metrics

pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/starter.go
This also proves that we're still working.
=> bug 1804439: clean up packages

pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go, pkg/operator/starter.go
picked up the changes missed from #139
=> Bug 1802664: *: fix etcdmemberscontroller

pkg/etcdcli/etcdcli.go, pkg/etcdcli/interfaces.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/clustermembercontroller/clustermembercontroller.go
=> bug 1804439: add debugging to clustermembercontroller and clean up add bug

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
replace bash logic with a command.
=> bug 1805807: call the discovery-etcd-initial-cluster

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, bindata/etcd/pod.yaml, pkg/cmd/render/options/config.go, pkg/cmd/render/render.go, pkg/cmd/render/render_test.go, pkg/etcdcli/etcdcli.go, pkg/operator/etcd_assets/bindata.go
we have a lot to bring back
and ipv6.  this brings us back to master and hopefully ipv6
=> bug 1805809: merge master into 4.4

pkg/operator/clustermembercontroller/clustermembercontroller.go
/hold
this exists just for clusterbot
=> [4.4] only add members when the etcd container is unready

bindata/etcd/etcd-member-remove.sh, bindata/etcd/etcd-restore-backup.sh, bindata/etcd/etcd-snapshot-backup.sh, bindata/etcd/openshift-recovery-tools, bindata/etcd/scripts-cm.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/scriptcontroller/scriptcontroller.go, pkg/operator/starter.go
Added the recovery scripts needed for Disaster Recovery in 4.4:
etcd-restore-backup.sh
etcd-snapshot-backup.sh
etcd-member-remove.sh
openshift-recovery-tools
=> [Bug 1807493]: Add recovery scripts to ceo

bindata/etcd/etcd-restore-backup.sh, bindata/etcd/scripts-cm.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/scriptcontroller/scriptcontroller.go, pkg/operator/starter.go
A starting point.
/assign @retroflexer
=> [Bug 1807493]: add scripts to files laid down to host

bindata/etcd/etcd-member-remove.sh, bindata/etcd/etcd-restore-backup.sh, bindata/etcd/etcd-snapshot-backup.sh, bindata/etcd/openshift-recovery-tools, bindata/etcd/restore-pod.yaml, bindata/etcd/scripts-cm.yaml, go.mod, go.sum, pkg/operator/etcd_assets/bindata.go, pkg/operator/scriptcontroller/scriptcontroller.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
[Bug 1807493]: Add recovery scripts to ceo
[Bug 1807493]: add the restore command to restore pod
[Bug 1807493]: update library-go for substitution
=> Bug 1807976: sync with master

pkg/operator/targetconfigcontroller/etcd_env.go
We need the ability to adjust etcd runtimes based on provider type. In the future, we could consider autotuning these based on metrics.
=> Bug 1806700: pkg/operator/targetconfigcontroller: add platform raft tunables

bindata/etcd/openshift-recovery-tools, bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/dnshelpers/util.go, pkg/etcdcli/etcdcli.go, pkg/etcdcli/interfaces.go, pkg/etcdenvvar/envvarcontroller.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go, pkg/operator/scriptcontroller/scriptcontroller.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
=> remove dns lookups

pkg/etcdcli/etcdcli.go
This may reduce log noise, but the etcd client has to be thread-safe
=> cache the client based on the endpoints to avoid reconstruction

Dockerfile.rhel7
Fix issues reported as breaking using buildah
=> Bug 1810181: Remove wildcard COPY form Docker

pkg/operator/starter.go
Signed-off-by: Tang Le <at28997146@163.com>
=> remove a duplicate line

bindata/etcd/pod.yaml, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/clustermembercontroller/clustermembercontroller_test.go, pkg/operator/etcd_assets/bindata.go
manually picking #293 and #296
=> Bug 1817071: *: add an init container to stop the pod with bad revision

go.mod, go.sum, manifests/0000_12_etcd-operator_03_configmap.yaml, manifests/0000_12_etcd-operator_06_deployment.yaml, pkg/operator/metriccontroller/client.go, vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/monitoring/bindata/bindata.go, vendor/modules.txt
=> Bug 1813894: Stop using service ca from service account token

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, pkg/cmd/render/env.go, pkg/cmd/render/env_test.go, pkg/cmd/render/render.go, pkg/etcdenvvar/etcd_env.go
(cherry picked from commit 97a975eeeddd9750c41f32cd82073ed77793cf8d)
=> Bug 1831664: pkg/cmd/render: Backport adding support for s390 and s390x arch

bindata/etcd/etcd-common-tools, pkg/operator/etcd_assets/bindata.go
This is a manual cherry pick of PR: https://github.com/openshift/cluster-etcd-operator/pull/320.
=> Bug 1825236: Fix podman auth

pkg/etcdcli/etcdcli.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go, pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go, pkg/operator/etcdmemberscontroller/etcdmemberscontroller_test.go
Cherry picking from PRs https://github.com/openshift/cluster-etcd-operator/pull/290 and https://github.com/openshift/cluster-etcd-operator/pull/318.
=> Bug 1823608: fix message reporting for etcdmemberscontroller

OWNERS
=> Bug 1836374: OWNERS: add Dan Mace and Suresh Kolichala 

pkg/etcdcli/etcdcli.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/starter.go
Supercedes https://github.com/openshift/cluster-etcd-operator/pull/237
=> Bug 1832923: remove bootstrap annotation after bootstrapping

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
Cherry-pick of https://github.com/openshift/cluster-etcd-operator/pull/356
=> Bug 1837630: pkg/operator/etcdcertsigner: sign etcd certs for 3 years

pkg/etcdcli/etcdcli.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/starter.go
Reverts openshift/cluster-etcd-operator#342
=> Bug 1832923: revert: remove bootstrap annotation after bootstrapping

pkg/etcdenvvar/etcd_env.go
The environment variable is used by default as the set of endpoints for all etcdctl commands. Including the bootstrap node, which is removed after the successful installation, results in reporting unexpected errors. 
We do not want to include initially and later remove it because triggering a revision is costly and the simpler solution would be to not include the bootstrap node in the first place.
=> Bug 1835238: Exclude bootstrap in the env variable ETCDCTL_ENDPOINTS

OWNERS
=> OWNERS: add sttts

manifests/0000_12_etcd-operator_00_namespace.yaml, manifests/0000_12_etcd-operator_01_config.crd.yaml, manifests/0000_12_etcd-operator_01_operator.cr.yaml, manifests/0000_12_etcd-operator_02_service.yaml, manifests/0000_12_etcd-operator_03_configmap.yaml, manifests/0000_12_etcd-operator_03_secret.yaml, manifests/0000_12_etcd-operator_04_clusterrolebinding.yaml, manifests/0000_12_etcd-operator_05_serviceaccount.yaml, manifests/0000_12_etcd-operator_06_deployment.yaml, manifests/0000_12_etcd-operator_07_clusteroperator.yaml, manifests/0000_12_etcd-operator_08_etcdquorumguard_deployment.yaml, manifests/0000_12_etcd-operator_09_etcdquorumguard_pdb.yaml, manifests/0000_90_etcd-operator_01_prometheusrole.yaml, manifests/0000_90_etcd-operator_02_prometheusrolebinding.yaml, manifests/0000_90_etcd-operator_03_servicemonitor.yaml
This is matches https://github.com/openshift/enhancements/pull/414 and doesn't change existing behavior
=> Bug 1871890: add current profile annotations to CVO manifests

pkg/operator/etcdmemberipmigrator/etcdmemberipmigrator.go
Some Azure IPI clusters were observed to have DNS forwarding rules which
delegated to upstreams not containing etcd records from the cluster private DNS
zone. Such configurations thwart the IP migration logic from performing a
reverse lookup of member IP addresses, causing the migration and thus the
upgrade to fail. Technically the upstream nameserver shares some blame for not
actually being authoritative for the private zone domain, but we can work around
it to save users from intervening.
This patch introduces a fallback means of etcd member IP determination used only
when the DNS method fails on Azure. In this case, we can exploit the member
naming conventions to statically map an etcd member to a node, and then assign
the member IP based on the node IP, bypassing DNS altogether.
=> Bug 1869681: handle IP migration when DNS fails on Azure IPI

OWNERS
we are not using `Etcd Operator` component.
=> OWNERS: change component to Etcd

manifests/0000_12_etcd-operator_10_flowschema.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
=> add current profile annotations to CVO manifests

bindata/etcd/cluster-backup.sh, pkg/operator/etcd_assets/bindata.go
Backport of https://github.com/openshift/cluster-etcd-operator/pull/371
=> Bug 1848516: cluster-backup.sh: error if script dependencies are not met

OWNERS
Maru is a member of the etcd team and has been extremely helpful with reviews. This PR adds him to reviewers.
Welcome to the Hotel California @marun :rocket:
=> OWNERS: add marun

pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
manual cherry-pick of #525  into release-4.6 superceeds #528
=> Bug 1917411: pkg/operator: ensure etcd endpoints configmap

docs/HACKING.md
added a small section to docs that cover gotchas we have run into recently.
=> docs: add maintenance section

pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go, vendor/modules.txt
This is a manual cherry-pick of #517 onto release-4.6
=> Bug 1915560: operator: remove EtcdMemberIPMigratorDegraded stale condition

pkg/operator/metriccontroller/fsync_controller.go
caught in CI[1],[2] thanks @trozet. The solution is to check success when casting variable. 
[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1042/pull-ci-openshift-cluster-network-operator-master-e2e-gcp-ovn-upgrade/1382687306791522304/artifacts/e2e-gcp-ovn-upgrade/gather-extra/artifacts/pods/openshift-etcd-operator_etcd-operator-7897fff8c9-njwzl_etcd-operator.log
[2] https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-network-operator/1042/pull-ci-openshift-cluster-network-operator-master-e2e-gcp-ovn-upgrade/1382687306791522304
=> Bug 1952684: pkg/operator/metriccontroller: dont panic on invalid response from prom client

OWNERS
Welcome to the etcd team @lilic!
=> OWNERS: add lilic as reviewer

pkg/dnshelpers/util.go
cluster-etcd-operator will fail to scale up if `network.Status.ServiceNetwork` is not populated. As per the bug[1] in this case the operator should fall back to `network.Spec.ServiceNetwork` vs fail. This PR provides that fallback mechanism. Net result of this failure can be a failed install.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1902247
/cc @danwinship  PTAL
=> Bug 1902247: pkg/dnshelpers: fallback to spec if status is not populated for serviceNetwork

pkg/dnshelpers/util.go
=> Bug 1902247: pkg/dnshelpers: cleanup dead code

bindata/etcd/cluster-backup.sh, bindata/etcd/cluster-restore.sh, bindata/etcd/etcd-common-tools, pkg/operator/etcd_assets/bindata.go
Backup and restore should perform consistency checks on etcd snapshots.
=> Bug 1965024: Validate the status of the etcd snapshot during backup and restore

go.mod, go.sum, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/scriptcontroller/scriptcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiregistration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/credentialsrequest.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/migration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/policy.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/rbac.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/unstructured.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/volumesnapshotclass.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go, vendor/github.com/openshift/library-go/pkg/operator/revisioncontroller/revision_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/k8s.io/client-go/restmapper/category_expansion.go, vendor/k8s.io/client-go/restmapper/discovery.go, vendor/k8s.io/client-go/restmapper/shortcut.go, vendor/modules.txt
Superceeds #615 due to merge conflict.
=> bump library-go to get context fixes

OWNERS
Thanks for everything @retroflexer !
=> OWNERS: goodbye Suresh

pkg/operator/targetconfigcontroller/targetconfigcontroller.go
The current code reports the invalid resource but does not block a new revision from being created. In the case that configmap openshift-config-managed/csr-controller-ca is not managed by cluster-kube-controller-manager-operator block if SNO. This will ensure we don't rollout and cause disruption before critical resource generation.
=> Bug 1989335: pkg/operator/targetconfigcontroller: block rollout and report on missing external resource

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
we don't need to advertise and it breaks some documented etcdctl commands using the --cluster flag
=> Bug 1993757: bindata/etcd: remove unix socket from advertised list

OWNERS
@lilic in a very short period of time has gained the trust of not only myself but all of group-b. Thanks and keep up the great work!
=> OWNERS: add lilic as approver.

bindata/etcd/cluster-backup-pod.yaml, bindata/etcd/etcd-common-tools, cmd/cluster-etcd-operator/main.go, pkg/cmd/verify/backupstorage.go, pkg/cmd/verify/verify.go, pkg/etcdcli/etcdcli.go, pkg/etcdcli/helpers.go, pkg/etcdcli/interfaces.go, pkg/operator/clustermembercontroller/clustermembercontroller_test.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go, pkg/operator/starter.go, pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go, pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go, pkg/testutils/testutils.go
Manual cherry-pick of #647 and #653
/hold
=> Bug 1999777: [release-4.8]: pkg/operator: add cluster backup upgrade controller

OWNERS
=> OWNERS: add hasbro17 to reviewers

pkg/etcdcli/etcdcli.go, pkg/etcdcli/helpers.go, pkg/etcdcli/interfaces.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/clustermembercontroller/clustermembercontroller_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go, pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
As part of the previous PR comment, this passes the context and adds it to the function signatures. 
@hasbro17 @hexfusion please take a look, thanks!
=> pkg: Pass context through to functions

pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
The backup directory name was incorrectly being regenerated when writing to the status condition.
It should now be read from the pod spec's env var which reflects the actual backup dir name.
TODO: Backport to 4.9 and 4.8 to fix https://bugzilla.redhat.com/show_bug.cgi?id=2004451
=> Bug 2004451: pkg/operator/upgradebackupcontroller: fix backup dir name in status condition

pkg/operator/metriccontroller/fsync_controller.go
Still want to test some things.
/hold
=> pkg/operator/metriccontroller: Fix query

OWNERS
Welcome to the team Allen :+1:
=> OWNERS: welcome Allen

cmd/cluster-etcd-operator/main.go, go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go, vendor/github.com/openshift/library-go/pkg/network/dialer_linux.go, vendor/github.com/openshift/library-go/pkg/network/dialer_others.go, vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go, vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go, vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go, vendor/github.com/openshift/library-go/pkg/operator/events/recorder_upstream.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go, vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/flock/flock_linux.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/internal/flock/flock_others.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/prune/cmd.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go, vendor/modules.txt
picks up openshift/library-go#1260 . Verified self-lgtm with @mfojtik in slack to get fixes overnight.
=> bump(library-go): to gather a fix for static pod UID version

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/bindata/bindata.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/guard/guard_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/modules.txt
Because of an issue which was found in [library-go,](https://github.com/openshift/library-go/pull/1272) and operator is affected, bumping it to the latest changes with the fix
=> Bump library-go

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/modules.txt
bringing in https://github.com/openshift/library-go/pull/1300
=> wait for other installers to finish

pkg/operator/metriccontroller/fsync_controller.go
https://bugzilla.redhat.com/show_bug.cgi?id=2057642
=> Bug 2057642: Change fsync degraded reason to CamelCase

bindata/bootkube/bootstrap-manifests/etcd-member-pod.yaml, bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
Something to talk about.  I don't fully understand what https://github.com/etcd-io/etcd/blob/main/server/etcdserver/corrupt.go#L39-L121 does yet.
/hold
holding until I understand the impacts and risks.
=> turn on initial corruption check

pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go
paves the way for https://github.com/openshift/cluster-etcd-operator/pull/779
=> refactors the member removal controller

pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
it attempts to remove a learning member pending deletion regardless of whether a replacement member has been found
=> adds attemptToRemoveLearningMember to the cluster member removal controller

OWNERS
Adding Mustafa and Emily to reviewers
=> Update owners with new team members

OWNERS
Adding Mustafa and Emily to reviewers
=> Bug 2076773: Update owners to add new team members

pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
otherwise, we might lose quorum since some members might be unavailable.
I think it doesn't matter for `removeMemberWithoutMachine` and  `attemptToRemoveLearningMember` methods.
=> clustermemberremovalcontroller must examine cluster health before removing a member

pkg/operator/defragcontroller/defragcontroller.go, pkg/operator/defragcontroller/defragcontroller_test.go, pkg/operator/starter.go, pkg/testutils/testutils.go
adding a flag configmap to stop defragmentation
=> Bug 2079724: manually disable defrag

pkg/etcdcli/etcdcli.go, pkg/operator/defragcontroller/defragcontroller.go
https://bugzilla.redhat.com/show_bug.cgi?id=2063183
=> Bug 2063183: Upping defrag timeout to 1 minute

pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go
https://bugzilla.redhat.com/show_bug.cgi?id=2061496
=> Bug 2061496: Adding message to ControllerStarted:RecentBackup condition

OWNERS
Backport of #815
https://bugzilla.redhat.com/show_bug.cgi?id=2082312
=> Bug 2082312: Adding Thomas to reviewers, adding Allen to approvers

OWNERS
Backport of #817 
https://bugzilla.redhat.com/show_bug.cgi?id=2082316
=> Bug 2082316: Add new etcd members to reviewers, add Allen to approvers

pkg/etcdcli/helpers.go, pkg/operator/defragcontroller/defragcontroller.go, pkg/operator/defragcontroller/defragcontroller_test.go
only let the defrag controller degrade after failing several attempts at actual defragmentation work
=> Bug 2073901: revisit defrag controller degradation

go.mod, go.sum, pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go, pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go, vendor/github.com/mcuadros/go-version/.gitignore, vendor/github.com/mcuadros/go-version/.travis.yml, vendor/github.com/mcuadros/go-version/LICENSE, vendor/github.com/mcuadros/go-version/README.md, vendor/github.com/mcuadros/go-version/compare.go, vendor/github.com/mcuadros/go-version/constraint.go, vendor/github.com/mcuadros/go-version/doc.go, vendor/github.com/mcuadros/go-version/group.go, vendor/github.com/mcuadros/go-version/normalize.go, vendor/github.com/mcuadros/go-version/sort.go, vendor/github.com/mcuadros/go-version/stability.go, vendor/modules.txt
This PR is a manual cherry pick of https://github.com/openshift/cluster-etcd-operator/pull/835
=> [release-4.10] Bug 2091604: Cherrypick create backup before each upgrade

pkg/etcdcli/health.go
more details can be found in a sister bug with similar problems:
https://bugzilla.redhat.com/show_bug.cgi?id=2090628#c10
=> Bug 2093819: add timeout to health checks

pkg/operator/upgradebackupcontroller/upgradebackupcontroller.go, pkg/operator/upgradebackupcontroller/upgradebackupcontroller_test.go
This is an cherry-pick of https://github.com/openshift/cluster-etcd-operator/pull/857
=> [release-4.10] Bug 2105148: fix degraded missing cluster version

hack/generate.sh, jsonnet/dashboard.jsonnet, jsonnet/jsonnetfile.lock.json, manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml
This PR migrates etcd grafana dashboard to CEO
cc @simonpasquier
=> Bug 2089199: Move etcd monitoring dashboards CEO

jsonnet/jsonnetfile.lock.json, jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet, jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
This PR vendors upstream `etcdExcessiveDatabaseGrowth` alert.
=> Bug 2097073: vendor upstream alerts

pkg/etcdcli/health.go, pkg/etcdenvvar/envvarcontroller.go, pkg/etcdenvvar/etcd_env.go, pkg/etcdenvvar/fake_envvar.go, pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/ceohelpers/control_plane_topology.go, pkg/operator/ceohelpers/qourum_check.go, pkg/operator/ceohelpers/qourum_check_test.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go, pkg/testutils/testutils.go
/hold
still testing and writing tests
=> Bug 2061062: ensure healthy quorum before config update

bindata/etcd/pod.yaml, cmd/cluster-etcd-operator/main.go, pkg/cmd/readyz/readyz.go, pkg/operator/etcd_assets/bindata.go
This is a manual cherry-pick of https://github.com/openshift/cluster-etcd-operator/pull/880
=> [release-4.9] Bug 2111432: Add etcd pod liveness and readiness probes

jsonnet/jsonnetfile.lock.json, jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/mixin.libsonnet, jsonnet/vendor/github.com/etcd-io/etcd/contrib/mixin/test.yaml, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
This PR brings recent changes in upstream etcd alerts
=> vendor upstream alerts

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
=> Set default container in etcd

jsonnet/dashboard.jsonnet, jsonnet/jsonnetfile.lock.json, manifests/0000_20_etcd-operator_00_namespace.yaml, manifests/0000_20_etcd-operator_01_operator.cr.yaml, manifests/0000_20_etcd-operator_02_service.yaml, manifests/0000_20_etcd-operator_03_configmap.yaml, manifests/0000_20_etcd-operator_03_secret.yaml, manifests/0000_20_etcd-operator_04_clusterrolebinding.yaml, manifests/0000_20_etcd-operator_05_serviceaccount.yaml, manifests/0000_20_etcd-operator_10_flowschema.yaml, manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml, manifests/0000_90_etcd-operator_01_prometheusrole.yaml, manifests/0000_90_etcd-operator_02_prometheusrolebinding.yaml, manifests/0000_90_etcd-operator_03_prometheusrule.yaml, manifests/0000_90_etcd-operator_03_servicemonitor.yaml
This PR is a manual cherry pick from https://github.com/openshift/cluster-etcd-operator/pull/897
=>  [release-4.11] Bug 2108595: Cherrypick remove etcd dashboards from Hypershift

pkg/dnshelpers/util.go, pkg/etcdcli/health.go, pkg/etcdenvvar/envvarcontroller.go, pkg/etcdenvvar/etcd_env.go, pkg/etcdenvvar/fake_envvar.go, pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/ceohelpers/control_plane_topology.go, pkg/operator/ceohelpers/qourum_check.go, pkg/operator/ceohelpers/qourum_check_test.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go, pkg/operator/starter.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller_test.go, pkg/testutils/testutils.go
=> [release-4.8] OCPBUGS-1230: ensure healthy quorum before config update

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
/hold
just want to check whether we can influence the niceness on etcd for CPU as well. This normally requires su privileges.
=> OCPBUGS-1329: Add niceness to important etcd processes

docs/access-clusterbot-resources.md
This PR adds a document explains how to access resources created by `cluster-bot` directly using `aws_cli`
=> doc access clusterbot resources

.gitignore, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
pick and fix of https://github.com/openshift/cluster-etcd-operator/pull/945
plus adding goland to gitignore as separate commit
=> OCPBUGS-2577: fix cert rotation on IP changes

pkg/etcdcli/helpers.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/defragcontroller/defragcontroller.go, pkg/operator/defragcontroller/defragcontroller_test.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
manual pick of https://github.com/openshift/cluster-etcd-operator/pull/812
plus some missing generated data on that branch, not sure how that happened....
=> OCPBUGS-2940: revisit defrag controller degradation

pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller_test.go, pkg/testutils/testutils.go
this is the unit tests without any (real) logic change to the delayed scaling requested in #951
=> add test for bootstrap teardown controller

pkg/tlshelpers/tlshelpers.go
This PR removes redundant certificate creation code and comments.
=> certificate code cleanup

pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go
fixes https://issues.redhat.com/browse/OCPBUGS-5304
=> OCPBUGS-5304: should not scale-down when all members are healthy

pkg/operator/bootstrapteardown/bootstrap_teardown_controller.go, pkg/operator/bootstrapteardown/bootstrap_teardown_controller_test.go
/hold
less complicated than  #991
=> OCPBUGS-5988: add dedicated success status for bootstrap removal

go.mod, pkg/etcdenvvar/envvarcontroller_test.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/ceohelpers/qourum_check.go, pkg/testutils/testutils.go
fixing #1000 and similar to #1001 with tests
=> fail early on missing node status envs

pkg/cmd/verify/backupstorage.go, pkg/etcdcli/etcdcli.go, pkg/etcdcli/etcdcli_pool.go
[for ceo connection timeout](https://github.com/openshift/cluster-etcd-operator/issues/1000)
=> [release-4.10] OCPBUGS-7827: set default timeouts in etcdcli

pkg/cmd/render/render.go, pkg/cmd/render/render_test.go
Previously we only supported v4-primary dual stack, so it was correct to always use ipv4 unless we were single stack v6. Now we need to add support for v6-primary dual stack so we need to be more nuanced about ip selection.
This change looks at the first CIDR to determine whether the cluster should be v4 or v6 primary. The other logic stays essentially the same since it was already set up to look for ipv6 addresses when required.
=> ETCD-385: Prefer ipv6 on bootstrap in v6-primary dual stack

hack/generate.sh, jsonnet/jsonnetfile.lock.json, jsonnet/removed_dashboard.jsonnet, manifests/0000_90_cluster-etcd-operator_02-removed-dashboard.yaml
this is a manual cherrypick of https://github.com/openshift/cluster-etcd-operator/pull/1016
resolves https://issues.redhat.com/browse/OCPBUGS-9908
=> [release-4.11] OCPBUGS-9908: Garbage collect grafana-dashboard-etcd

pkg/operator/bootstrapteardown/bootstrap_teardown_controller_test.go, pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/ceohelpers/common_test.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go, pkg/operator/starter.go, pkg/testutils/testutils.go
resolves https://issues.redhat.com/browse/OCPBUGS-10351 
cc @tjungblu @hasbro17 @wking @damdo
=> OCPBUGS-10351: skip machine deletion during boostrap

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/staticpod/installerpod/cmd.go, vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go, vendor/modules.txt
=> OCPBUGS-14323: Change manifest directory permissions

hack/featuregate_backup.yaml, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/hardcoded_featuregate_reader.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/observe_featuregates.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/simple_featuregate_reader.go, vendor/modules.txt
requirement for logic in [ETCD-436](https://issues.redhat.com/browse/ETCD-436)
=> Integrate feature flags in CEO

pkg/operator/ceohelpers/machine_api.go, pkg/operator/ceohelpers/machine_api_test.go, pkg/operator/clustermembercontroller/clustermembercontroller.go, pkg/operator/clustermembercontroller/clustermembercontroller_test.go, pkg/operator/clustermemberremovalcontroller/clustermemberremovalcontroller_test.go, pkg/operator/machinedeletionhooks/machinedeletionhooks_test.go, pkg/operator/starter.go
/hold
still missing informer support and still testing
=> OCPBUGS-16889: handle optional machineAPI

hack/backup_pv_pvc.yaml
This adds yaml for backup default pv & pvc.
=> add backup pv pvc yaml

pkg/operator/backupcontroller/backupcontroller.go, pkg/operator/backupcontroller/backupcontroller_test.go
Thanks for finding this @Elbehery 
/assign @Elbehery
=> add processed label to skipped backups

pkg/cmd/prune-backups/prune.go, pkg/cmd/prune-backups/prune_test.go, test/e2e/backup_test.go, test/e2e/etcdctl_test.go
/hold
still debugging, probably some silly default value
=> e2e test for size retention

test/e2e/backup_test.go
that tests that the operator will degrade when a faulty cronjob was pushed to the API and recovers when removed.
=> add e2e test for cronjob reconciliation failures

jsonnet/dashboard.jsonnet, jsonnet/diskjitter_dashboard.json, manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml
resolves https://issues.redhat.com/browse/ETCD-435 
cc @tjungblu @hasbro17 @wking @simonpasquier
=> [release-4.14] OCPBUGS-18166: add etcd diskjitter dashboards

test/e2e/backup_script_test.go
resolves https://issues.redhat.com/browse/ETCD-484
=> ETCD-484: add e2e backup debug pod

bindata/etcd/backups-cr.yaml, bindata/etcd/cluster-backup-cronjob.yaml, pkg/cmd/request-backup/requestbackup.go, pkg/operator/backupcontroller/backup_removal_controller.go, pkg/operator/backupcontroller/backup_removal_controller_test.go, pkg/operator/backupcontroller/backupcontroller.go, pkg/operator/backupcontroller/backupcontroller_test.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/starter.go, test/e2e/backup_test.go
/hold
still need to write more tests
=> OCPBUGS-19528: introduce backup removal controller

jsonnet/cpu_iowait_dashboard.json, jsonnet/dashboard.jsonnet, manifests/0000_90_cluster-etcd-operator_01-dashboards.yaml
resolves https://issues.redhat.com/browse/ETCD-187
=> ETCD-187: add dashboards CPU iotwait on master nodes

bindata/etcd/cluster-backup.sh, bindata/etcd/cluster-restore.sh, bindata/etcd/etcd-common-tools, bindata/etcd/restore-pod.yaml, pkg/operator/etcd_assets/bindata.go, test/e2e/backup_script_test.go, test/e2e/backup_test.go, test/e2e/framework/clientset.go
adds #1136 into #1130 for a proper 4.12 backport.
=> OCPBUGS-20100: [4.12] Backports of backup/restore fixes

pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
Reverts openshift/cluster-etcd-operator#1087
=> Revert "OCPBUGS-17199: remove revision stability check from bootstrap complet…"

pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
Reverts openshift/cluster-etcd-operator#1138
=> Revert "[release-4.14] OCPBUGS-21802: remove revision stability check from bootstrap complet…"

pkg/etcdcli/cached_members.go, pkg/etcdcli/cached_members_test.go, pkg/etcdcli/etcdcli.go, pkg/etcdcli/health.go, pkg/etcdcli/interfaces.go, pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/qourum_check.go, pkg/operator/defragcontroller/defragcontroller.go, pkg/operator/defragcontroller/defragcontroller_test.go, pkg/operator/etcdmemberscontroller/etcdmemberscontroller.go, pkg/operator/starter.go
resolves https://issues.redhat.com/browse/ETCD-349
=> ETCD-349: add etcd cachedmembers

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
=> NO-JIRA: fail certsignercontroller sync when secret can not be applied

jsonnet/custom.libsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml, pkg/cmd/render/certs.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/starter.go
/hold
need to add an alert as well
=> ETCD-583: add signer expiration metric and alert

bindata/etcd/pod.yaml, pkg/operator/etcd_assets/bindata.go
resolves https://issues.redhat.com/browse/OCPBUGS-31249
=> OCPBUGS-31249: remove etcd-health-probe log

pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
address https://github.com/openshift/cluster-etcd-operator/issues/1240  and https://github.com/openshift/cluster-etcd-operator/issues/1237
=> OCPBUGS-31849: check the quorum in case the cluster is healthy or not after generating certs

bindata/etcd/pod.yaml, bindata/etcd/restore-pod.yaml, pkg/cmd/operator/cmd.go, pkg/cmd/render/certs_test.go, pkg/etcdenvvar/envvarcontroller_test.go, pkg/etcdenvvar/etcd_env.go, pkg/operator/etcd_assets/bindata.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/operator/starter.go, pkg/tlshelpers/tlshelpers.go
code from #1268 with vendor of https://github.com/openshift/library-go/pull/1739 for testing
/hold
=> ETCD-606: Batch bundle revision rollout 

docs/etcd-tls-assets.md
=> NO-JIRA: Update etcd-tls-assets.md

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/prune/prune_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/staticpodstate/staticpodstate_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go, vendor/modules.txt
for https://github.com/openshift/library-go/pull/1743 and https://github.com/openshift/library-go/pull/1724
=> NO-JIRA: update library-go

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go
on CEO restart the informer is sometimes not synchronized, which causes premature leaf cert generation as the bootstrap thinks it's not done yet.
=> NO-JIRA: fix false positive bootstrap in cert signer controller

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go, pkg/tlshelpers/tlshelpers.go
During vertical scaling we could hit a case where the signers are expired and would trigger a rotation, even though we only wanted to create a new set of peer certs. This can cause bricked clusters, as there is no safe guard for the bundle distribution in this case.
/hold 
waiting for the test suite to merge first, even though it might not be relevant
=> NO-JIRA: only read signer/bundles on forced leaf generation

manifests/0000_20_etcd-operator_03_configmap.yaml
Reverts openshift/cluster-etcd-operator#1293
leaving this here as this is not effectively fixing the issue
=> Revert "OCPBUGS-36621: add etcd-all-bundles to cvo create-only"

pkg/operator/etcdcertsigner/etcdcertsignercontroller.go, pkg/operator/etcdcertsigner/etcdcertsignercontroller_test.go
The etcdcertsigner controller would previously not run if a revision rollout was already in progress which is necessary for the distribution of CA before leaf cert generation during a CA rotation. However in the event where there is no cert rotation ongoing and the etcd-all-bundles configmap is missing the revision rollout can get stuck as the installer pod won't find the etcd-all-bundles configmap to install on disk.
In that case the etcdcertsigner controller would never generate the etcd-all-bundles configmap as it waits for the revision rollout that's in turn waiting on the configmap to be present.
This commit adds an override to let the controller sync and regenerate the configmap if it's missing similar to how the controller runs during the bootstrap phase.
=> OCPBUGS-36621: Force sync on missing etcd-all-bundles configmap

pkg/etcdcli/etcdcli.go, pkg/etcdcli/etcdcli_pool_test.go, pkg/etcdcli/health.go
This should reduce CPU consumption because of less TLS handshakes and makes it usable from other places too.
This is fixing the reverted patch by supplying a pool to the GetMemberHealth to avoid multiple goroutines changing the endpoints inadvertently
=> OCPBUGS-38573: use pooled client for etcd single member health checks

bindata/etcd/cluster-restore.sh, bindata/etcd/etcd-common-tools, bindata/etcd/quorum-restore-pod.yaml, bindata/etcd/quorum-restore.sh, bindata/etcd/scripts-cm.yaml, pkg/operator/etcd_assets/bindata.go, pkg/operator/scriptcontroller/scriptcontroller.go, pkg/operator/targetconfigcontroller/targetconfigcontroller.go
starting with the rough skeletons around a potential restoration experience for quorum loss scenarios.
/hold
=> ETCD-654: start with quorum restore script

pkg/cmd/backuprestore/backupserver.go, pkg/cmd/backuprestore/backupserver_test.go, pkg/cmd/prune-backups/prune.go, pkg/cmd/prune-backups/prune_test.go
resolves https://issues.redhat.com/browse/ETCD-666
=> ETCD-666: Add etcd-backup-server pruning logic

Dockerfile.ocp
test with https://github.com/openshift/api/pull/2030
=> create CRDs from openshift/api

pkg/cmd/backuprestore/backupserver.go
follow up on https://github.com/openshift/cluster-etcd-operator/pull/1340
=> ETCD-662: fix: etcd-backup-server prune path

pkg/backuphelpers/backupvars.go, pkg/cmd/backuprestore/backupserver.go, pkg/operator/periodicbackupcontroller/periodicbackupcontroller.go, pkg/operator/periodicbackupcontroller/periodicbackupcontroller_test.go, pkg/operator/starter.go
Resolves https://issues.redhat.com/browse/ETCD-679
cc @openshift/openshift-team-etcd @vrutkovs
=> ETCD-679: Add etcd backup server container failure resolution

pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/etcdendpointscontroller/etcdendpointscontroller_test.go
…eck"
This reverts commit 28467760b688785bf62a463b5ba545892cbd9471, reversing changes made to 52cac6a07da30a239e370311fac9052ba393505a.
=> OCPBUGS-17199:  Revert pull request https://github.com/openshift/cluster-etcd-operator/issues/1350

go.mod, go.sum, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/apiserver/jsonpatch/jsonpatch.go, vendor/github.com/openshift/library-go/pkg/crypto/crypto.go, vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go, vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_staticpod_operator_client.go, vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/test_operator_client.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/monitoring.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go, vendor/github.com/openshift/library-go/pkg/operator/staticpod/controllers.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/canonicalize.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/interfaces.go, vendor/github.com/openshift/library-go/pkg/operator/v1helpers/test_helpers.go, vendor/modules.txt
- **bump library-go**
- **use new NewStaticPodOperatorClient signature**
=> NO-JIRA: bump library-go

pkg/operator/ceohelpers/bootstrap.go, pkg/operator/ceohelpers/bootstrap_test.go, pkg/operator/ceohelpers/qourum_check.go, pkg/operator/ceohelpers/qourum_check_test.go, pkg/operator/starter.go
=> OCPBUGS-42809: always ensure quorum during bootstrap

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
resolves https://issues.redhat.com/browse/OCPBUGS-53512
=> OCPBUGS-53512: fix CVE-2025-30204

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
resolves https://issues.redhat.com/browse/OCPBUGS-53513
=> OCPBUGS-53513: fix CVE-2025-30204

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
resolves https://issues.redhat.com/browse/OCPBUGS-53511
=> OCPBUGS-53511: fix CVE-2025-30204

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
resolves https://issues.redhat.com/browse/OCPBUGS-53510
=> OCPBUGS-53510: fix CVE-2025-30204

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
resolves https://issues.redhat.com/browse/OCPBUGS-53506
=> OCPBUGS-53506: fix CVE-2025-30204

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/modules.txt
resolves https://issues.redhat.com/browse/OCPBUGS-53507
=> OCPBUGS-53507: fix CVE-2025-30204

go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/README.md, vendor/github.com/golang-jwt/jwt/v4/claims.go, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/github.com/golang-jwt/jwt/v4/token.go, vendor/modules.txt
=> OCPBUGS-53508: fix CVE-2025-30204

jsonnet/custom.libsonnet, manifests/0000_90_etcd-operator_03_prometheusrule.yaml
resolves https://issues.redhat.com/browse/OCPBUGS-55757
cc @wking @sdodson @tjungblu
=> OCPBUGS-55757: adjust alerts according to platform
